
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
// Generated on: May  6 2016 15:31:56

// Verification Directory fv/input_block 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module input_block(clk, bin_in, bin_out, bin_int_out, reset, valid,
     mode);
  input clk, bin_in, reset;
  output bin_out, bin_int_out, valid, mode;
  wire clk, bin_in, reset;
  wire bin_out, bin_int_out, valid, mode;
  wire [11:0] b0_addr1;
  wire [11:0] b0_addr2;
  wire [11:0] b1_addr1;
  wire [11:0] b1_addr2;
  wire [11:0] rom_counter;
  wire [11:0] addr2_tmp;
  wire [11:0] rd_counter;
  wire [11:0] counter;
  wire [2:0] Term_Counter;
  wire Dev1_State, DevEn0, DevEn1, RdWr0, RdWr1, UNCONNECTED,
       UNCONNECTED0, UNCONNECTED1;
  wire UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9;
  wire UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13,
       UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40, UNCONNECTED41;
  wire UNCONNECTED42, UNCONNECTED43, UNCONNECTED44, UNCONNECTED45,
       UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, b0_out0;
  wire b0_out1, b1_out0, b1_out1, bin_in_tmp, current_block, n_0, n_1,
       n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_205;
  wire n_261, n_262, n_263, n_266, n_268, n_269, n_270, n_271;
  wire n_272, n_274, n_275, n_276, n_277, rc_gclk, rc_gclk_4697,
       rc_gclk_4699;
  wire rc_gclk_4701;
  SRAM10T Buffer_0(.clk (n_266), .addr1 (b0_addr1), .addr2 (b0_addr2),
       .readLine1 (b0_out0), .readLine2 (b0_out1), .writeLine
       (bin_in_tmp), .RdWr (RdWr0), .DevEn (DevEn0));
  SRAM10T Buffer_1(.clk (n_266), .addr1 (b1_addr1), .addr2 (b1_addr2),
       .readLine1 (b1_out0), .readLine2 (b1_out1), .writeLine
       (bin_in_tmp), .RdWr (RdWr1), .DevEn (DevEn1));
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_263), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_261), .ck_in (clk), .ck_out
       (rc_gclk_4697), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_262), .ck_in (clk), .ck_out
       (rc_gclk_4699), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_269), .ck_in (clk), .ck_out
       (rc_gclk_4701), .test (1'b0));
  AddrEncoder ROM(.clk (clk), .in (rom_counter), .out (addr2_tmp));
  TLATX1 \b0_addr1_reg[0] (.G (n_203), .D (n_174), .Q (b0_addr1[0]),
       .QN (UNCONNECTED));
  TLATX1 \b0_addr1_reg[10] (.G (n_203), .D (n_196), .Q (b0_addr1[10]),
       .QN (UNCONNECTED0));
  TLATX1 \b0_addr1_reg[11] (.G (n_203), .D (n_195), .Q (b0_addr1[11]),
       .QN (UNCONNECTED1));
  TLATX1 \b0_addr1_reg[1] (.G (n_203), .D (n_194), .Q (b0_addr1[1]),
       .QN (UNCONNECTED2));
  TLATX1 \b0_addr1_reg[2] (.G (n_203), .D (n_193), .Q (b0_addr1[2]),
       .QN (UNCONNECTED3));
  TLATX1 \b0_addr1_reg[3] (.G (n_203), .D (n_192), .Q (b0_addr1[3]),
       .QN (UNCONNECTED4));
  TLATX1 \b0_addr1_reg[4] (.G (n_203), .D (n_191), .Q (b0_addr1[4]),
       .QN (UNCONNECTED5));
  TLATX1 \b0_addr1_reg[5] (.G (n_203), .D (n_190), .Q (b0_addr1[5]),
       .QN (UNCONNECTED6));
  TLATX1 \b0_addr1_reg[6] (.G (n_203), .D (n_189), .Q (b0_addr1[6]),
       .QN (UNCONNECTED7));
  TLATX1 \b0_addr1_reg[7] (.G (n_203), .D (n_188), .Q (b0_addr1[7]),
       .QN (UNCONNECTED8));
  TLATX1 \b0_addr1_reg[8] (.G (n_203), .D (n_187), .Q (b0_addr1[8]),
       .QN (UNCONNECTED9));
  TLATX1 \b0_addr1_reg[9] (.G (n_203), .D (n_186), .Q (b0_addr1[9]),
       .QN (UNCONNECTED10));
  TLATX1 \b0_addr2_reg[0] (.G (n_199), .D (n_165), .Q (b0_addr2[0]),
       .QN (UNCONNECTED11));
  TLATX1 \b0_addr2_reg[10] (.G (n_199), .D (n_169), .Q (b0_addr2[10]),
       .QN (UNCONNECTED12));
  TLATX1 \b0_addr2_reg[11] (.G (n_199), .D (n_164), .Q (b0_addr2[11]),
       .QN (UNCONNECTED13));
  TLATX1 \b0_addr2_reg[1] (.G (n_199), .D (n_168), .Q (b0_addr2[1]),
       .QN (UNCONNECTED14));
  TLATX1 \b0_addr2_reg[2] (.G (n_199), .D (n_163), .Q (b0_addr2[2]),
       .QN (UNCONNECTED15));
  TLATX1 \b0_addr2_reg[3] (.G (n_199), .D (n_162), .Q (b0_addr2[3]),
       .QN (UNCONNECTED16));
  TLATX1 \b0_addr2_reg[4] (.G (n_199), .D (n_161), .Q (b0_addr2[4]),
       .QN (UNCONNECTED17));
  TLATX1 \b0_addr2_reg[5] (.G (n_199), .D (n_167), .Q (b0_addr2[5]),
       .QN (UNCONNECTED18));
  TLATX1 \b0_addr2_reg[6] (.G (n_199), .D (n_166), .Q (b0_addr2[6]),
       .QN (UNCONNECTED19));
  TLATX1 \b0_addr2_reg[7] (.G (n_199), .D (n_170), .Q (b0_addr2[7]),
       .QN (UNCONNECTED20));
  TLATX1 \b0_addr2_reg[8] (.G (n_199), .D (n_160), .Q (b0_addr2[8]),
       .QN (UNCONNECTED21));
  TLATX1 \b0_addr2_reg[9] (.G (n_199), .D (n_171), .Q (b0_addr2[9]),
       .QN (UNCONNECTED22));
  TLATX1 \b1_addr1_reg[0] (.G (n_202), .D (n_185), .Q (b1_addr1[0]),
       .QN (UNCONNECTED23));
  TLATX1 \b1_addr1_reg[10] (.G (n_202), .D (n_197), .Q (b1_addr1[10]),
       .QN (UNCONNECTED24));
  TLATX1 \b1_addr1_reg[11] (.G (n_202), .D (n_184), .Q (b1_addr1[11]),
       .QN (UNCONNECTED25));
  TLATX1 \b1_addr1_reg[1] (.G (n_202), .D (n_183), .Q (b1_addr1[1]),
       .QN (UNCONNECTED26));
  TLATX1 \b1_addr1_reg[2] (.G (n_202), .D (n_182), .Q (b1_addr1[2]),
       .QN (UNCONNECTED27));
  TLATX1 \b1_addr1_reg[3] (.G (n_202), .D (n_181), .Q (b1_addr1[3]),
       .QN (UNCONNECTED28));
  TLATX1 \b1_addr1_reg[4] (.G (n_202), .D (n_180), .Q (b1_addr1[4]),
       .QN (UNCONNECTED29));
  TLATX1 \b1_addr1_reg[5] (.G (n_202), .D (n_179), .Q (b1_addr1[5]),
       .QN (UNCONNECTED30));
  TLATX1 \b1_addr1_reg[6] (.G (n_202), .D (n_178), .Q (b1_addr1[6]),
       .QN (UNCONNECTED31));
  TLATX1 \b1_addr1_reg[7] (.G (n_202), .D (n_177), .Q (b1_addr1[7]),
       .QN (UNCONNECTED32));
  TLATX1 \b1_addr1_reg[8] (.G (n_202), .D (n_176), .Q (b1_addr1[8]),
       .QN (UNCONNECTED33));
  TLATX1 \b1_addr1_reg[9] (.G (n_202), .D (n_175), .Q (b1_addr1[9]),
       .QN (UNCONNECTED34));
  TLATX1 \b1_addr2_reg[0] (.G (n_198), .D (n_165), .Q (b1_addr2[0]),
       .QN (UNCONNECTED35));
  TLATX1 \b1_addr2_reg[10] (.G (n_198), .D (n_169), .Q (b1_addr2[10]),
       .QN (UNCONNECTED36));
  TLATX1 \b1_addr2_reg[11] (.G (n_198), .D (n_164), .Q (b1_addr2[11]),
       .QN (UNCONNECTED37));
  TLATX1 \b1_addr2_reg[1] (.G (n_198), .D (n_168), .Q (b1_addr2[1]),
       .QN (UNCONNECTED38));
  TLATX1 \b1_addr2_reg[2] (.G (n_198), .D (n_163), .Q (b1_addr2[2]),
       .QN (UNCONNECTED39));
  TLATX1 \b1_addr2_reg[3] (.G (n_198), .D (n_162), .Q (b1_addr2[3]),
       .QN (UNCONNECTED40));
  TLATX1 \b1_addr2_reg[4] (.G (n_198), .D (n_161), .Q (b1_addr2[4]),
       .QN (UNCONNECTED41));
  TLATX1 \b1_addr2_reg[5] (.G (n_198), .D (n_167), .Q (b1_addr2[5]),
       .QN (UNCONNECTED42));
  TLATX1 \b1_addr2_reg[6] (.G (n_198), .D (n_166), .Q (b1_addr2[6]),
       .QN (UNCONNECTED43));
  TLATX1 \b1_addr2_reg[7] (.G (n_198), .D (n_170), .Q (b1_addr2[7]),
       .QN (UNCONNECTED44));
  TLATX1 \b1_addr2_reg[8] (.G (n_198), .D (n_160), .Q (b1_addr2[8]),
       .QN (UNCONNECTED45));
  TLATX1 \b1_addr2_reg[9] (.G (n_198), .D (n_171), .Q (b1_addr2[9]),
       .QN (UNCONNECTED46));
  DFFHQX1 bin_in_tmp_reg(.CK (clk), .D (bin_in), .Q (bin_in_tmp));
  DFFTRX1 bin_int_out_reg(.CK (clk), .D (n_271), .RN (n_173), .Q
       (UNCONNECTED47), .QN (n_201));
  DFFTRX1 bin_out_reg(.CK (clk), .D (n_271), .RN (n_172), .Q
       (UNCONNECTED48), .QN (n_200));
  NAND2BX1 g3202(.AN (n_263), .B (n_271), .Y (n_261));
  OR2X1 g3203(.A (n_263), .B (n_159), .Y (n_262));
  INVX12 g3228(.A (n_201), .Y (bin_int_out));
  INVX12 g3230(.A (n_200), .Y (bin_out));
  NAND2BX1 g3233(.AN (n_205), .B (n_147), .Y (n_263));
  NAND2BX1 g3258(.AN (n_270), .B (n_147), .Y (n_268));
  AO22X1 g3259(.A0 (n_143), .A1 (rd_counter[10]), .B0 (n_146), .B1
       (counter[10]), .Y (n_197));
  AO22X1 g3260(.A0 (n_142), .A1 (counter[10]), .B0 (n_145), .B1
       (rd_counter[10]), .Y (n_196));
  AO22X1 g3261(.A0 (n_157), .A1 (counter[11]), .B0 (n_158), .B1
       (rd_counter[11]), .Y (n_195));
  AO22X1 g3262(.A0 (n_143), .A1 (counter[1]), .B0 (n_146), .B1
       (rd_counter[1]), .Y (n_194));
  AO22X1 g3263(.A0 (n_141), .A1 (counter[2]), .B0 (n_144), .B1
       (rd_counter[2]), .Y (n_193));
  AO22X1 g3264(.A0 (n_143), .A1 (counter[3]), .B0 (n_146), .B1
       (rd_counter[3]), .Y (n_192));
  AO22X1 g3265(.A0 (n_157), .A1 (counter[4]), .B0 (n_158), .B1
       (rd_counter[4]), .Y (n_191));
  AO22X1 g3266(.A0 (n_143), .A1 (counter[5]), .B0 (n_146), .B1
       (rd_counter[5]), .Y (n_190));
  AO22X1 g3267(.A0 (n_142), .A1 (counter[6]), .B0 (n_145), .B1
       (rd_counter[6]), .Y (n_189));
  AO22X1 g3268(.A0 (n_142), .A1 (counter[7]), .B0 (n_145), .B1
       (rd_counter[7]), .Y (n_188));
  AO22X1 g3269(.A0 (n_142), .A1 (counter[8]), .B0 (n_145), .B1
       (rd_counter[8]), .Y (n_187));
  AO22X1 g3270(.A0 (n_141), .A1 (counter[9]), .B0 (n_144), .B1
       (rd_counter[9]), .Y (n_186));
  AO22X1 g3271(.A0 (n_141), .A1 (rd_counter[0]), .B0 (n_144), .B1
       (counter[0]), .Y (n_185));
  NAND2BX1 g3272(.AN (n_271), .B (n_147), .Y (n_274));
  AO22X1 g3273(.A0 (n_141), .A1 (rd_counter[11]), .B0 (n_144), .B1
       (counter[11]), .Y (n_184));
  AO22X1 g3274(.A0 (n_143), .A1 (rd_counter[1]), .B0 (n_146), .B1
       (counter[1]), .Y (n_183));
  AO22X1 g3275(.A0 (n_141), .A1 (rd_counter[2]), .B0 (n_144), .B1
       (counter[2]), .Y (n_182));
  AO22X1 g3276(.A0 (n_143), .A1 (rd_counter[3]), .B0 (n_146), .B1
       (counter[3]), .Y (n_181));
  AO22X1 g3277(.A0 (n_141), .A1 (rd_counter[4]), .B0 (n_144), .B1
       (counter[4]), .Y (n_180));
  AO22X1 g3278(.A0 (n_157), .A1 (rd_counter[5]), .B0 (n_158), .B1
       (counter[5]), .Y (n_179));
  AO22X1 g3279(.A0 (n_157), .A1 (rd_counter[6]), .B0 (n_158), .B1
       (counter[6]), .Y (n_178));
  AO22X1 g3280(.A0 (n_157), .A1 (rd_counter[7]), .B0 (n_158), .B1
       (counter[7]), .Y (n_177));
  AO22X1 g3281(.A0 (n_142), .A1 (rd_counter[8]), .B0 (n_145), .B1
       (counter[8]), .Y (n_176));
  AO22X1 g3282(.A0 (n_142), .A1 (rd_counter[9]), .B0 (n_145), .B1
       (counter[9]), .Y (n_175));
  AO22X1 g3283(.A0 (n_143), .A1 (counter[0]), .B0 (n_146), .B1
       (rd_counter[0]), .Y (n_174));
  NAND2X1 g3284(.A (n_155), .B (n_270), .Y (n_205));
  NAND2BX1 g3285(.AN (Term_Counter[0]), .B (n_159), .Y (n_272));
  NAND2X2 g3286(.A (Term_Counter[0]), .B (n_159), .Y (n_271));
  OR2X1 g3287(.A (n_152), .B (n_150), .Y (n_203));
  OR2X1 g3288(.A (n_149), .B (n_156), .Y (n_202));
  MX2X1 g3289(.A (b1_out1), .B (b0_out1), .S0 (current_block), .Y
       (n_173));
  MX2X1 g3290(.A (b1_out0), .B (b0_out0), .S0 (current_block), .Y
       (n_172));
  OR3X1 g3291(.A (Term_Counter[2]), .B (Term_Counter[0]), .C (n_153),
       .Y (n_270));
  AO21X1 g3292(.A0 (n_152), .A1 (current_block), .B0 (n_148), .Y
       (n_199));
  AO21X1 g3293(.A0 (n_156), .A1 (n_151), .B0 (n_148), .Y (n_198));
  OR2X1 g3294(.A (n_148), .B (n_147), .Y (n_269));
  AND2X1 g3296(.A (n_154), .B (addr2_tmp[9]), .Y (n_171));
  AND2X1 g3297(.A (n_154), .B (addr2_tmp[7]), .Y (n_170));
  AND2X1 g3298(.A (n_154), .B (addr2_tmp[10]), .Y (n_169));
  AND2X1 g3299(.A (n_155), .B (addr2_tmp[1]), .Y (n_168));
  AND2X1 g3300(.A (n_155), .B (addr2_tmp[5]), .Y (n_167));
  AND2X1 g3301(.A (n_154), .B (addr2_tmp[6]), .Y (n_166));
  AND2X1 g3302(.A (n_155), .B (addr2_tmp[0]), .Y (n_165));
  AND2X1 g3306(.A (n_155), .B (addr2_tmp[11]), .Y (n_164));
  AND2X1 g3307(.A (n_154), .B (addr2_tmp[2]), .Y (n_163));
  AND2X1 g3308(.A (n_154), .B (addr2_tmp[3]), .Y (n_162));
  AND2X1 g3309(.A (n_155), .B (addr2_tmp[4]), .Y (n_161));
  AND2X1 g3310(.A (n_154), .B (addr2_tmp[8]), .Y (n_160));
  NOR2X1 g3311(.A (Term_Counter[2]), .B (Term_Counter[1]), .Y (n_159));
  AND2X1 g3312(.A (n_154), .B (current_block), .Y (n_158));
  AND2X1 g3313(.A (n_155), .B (n_151), .Y (n_157));
  INVX1 g3314(.A (DevEn1), .Y (n_156));
  INVX1 g3315(.A (n_148), .Y (n_155));
  INVX1 g3316(.A (n_148), .Y (n_154));
  BUFX2 g3320(.A (reset), .Y (n_148));
  INVX1 g3322(.A (clk), .Y (n_266));
  INVX1 g3323(.A (Term_Counter[1]), .Y (n_153));
  INVX1 g3324(.A (DevEn0), .Y (n_152));
  INVX1 g3325(.A (current_block), .Y (n_151));
  BUFX2 drc_bufs3338(.A (mode), .Y (n_147));
  INVX1 drc_bufs3342(.A (n_150), .Y (n_146));
  INVX1 drc_bufs3343(.A (n_150), .Y (n_145));
  INVX1 drc_bufs3344(.A (n_150), .Y (n_144));
  INVX1 drc_bufs3345(.A (n_158), .Y (n_150));
  INVX1 drc_bufs3350(.A (n_149), .Y (n_143));
  INVX1 drc_bufs3351(.A (n_149), .Y (n_142));
  INVX1 drc_bufs3352(.A (n_149), .Y (n_141));
  INVX1 drc_bufs3353(.A (n_157), .Y (n_149));
  NAND2BX1 g2(.AN (reset), .B (counter[4]), .Y (n_275));
  SDFFQX1 Dev1_State_reg(.CK (rc_gclk_4699), .D (Dev1_State), .SI
       (DevEn1), .SE (n_12), .Q (Dev1_State));
  EDFFHQX1 DevEn0_reg(.CK (rc_gclk_4699), .D (n_27), .E (n_25), .Q
       (DevEn0));
  SMDFFHQX1 DevEn1_reg(.CK (rc_gclk_4699), .D0 (n_17), .D1 (n_18), .S0
       (n_4), .SE (n_24), .SI (DevEn1), .Q (DevEn1));
  SDFFQX1 RdWr0_reg(.CK (clk), .D (RdWr0), .SI (n_94), .SE (n_92), .Q
       (RdWr0));
  SDFFQX1 RdWr1_reg(.CK (clk), .D (RdWr1), .SI (n_93), .SE (n_92), .Q
       (RdWr1));
  DFFHQX1 \Term_Counter_reg[0] (.CK (rc_gclk_4701), .D (n_23), .Q
       (Term_Counter[0]));
  DFFHQX1 \Term_Counter_reg[1] (.CK (rc_gclk_4701), .D (n_276), .Q
       (Term_Counter[1]));
  DFFQXL \Term_Counter_reg[2] (.CK (rc_gclk_4701), .D (n_38), .Q
       (Term_Counter[2]));
  DFFQXL \counter_reg[0] (.CK (rc_gclk), .D (n_26), .Q (counter[0]));
  DFFQXL \counter_reg[10] (.CK (rc_gclk), .D (n_129), .Q (counter[10]));
  DFFHQX1 \counter_reg[11] (.CK (rc_gclk), .D (n_135), .Q
       (counter[11]));
  DFFQXL \counter_reg[1] (.CK (rc_gclk), .D (n_37), .Q (counter[1]));
  DFFQXL \counter_reg[2] (.CK (rc_gclk), .D (n_48), .Q (counter[2]));
  DFFQXL \counter_reg[3] (.CK (rc_gclk), .D (n_57), .Q (counter[3]));
  DFFQXL \counter_reg[4] (.CK (rc_gclk), .D (n_67), .Q (counter[4]));
  DFFQXL \counter_reg[5] (.CK (rc_gclk), .D (n_77), .Q (counter[5]));
  DFFQXL \counter_reg[6] (.CK (rc_gclk), .D (n_88), .Q (counter[6]));
  DFFQXL \counter_reg[7] (.CK (rc_gclk), .D (n_101), .Q (counter[7]));
  DFFQXL \counter_reg[8] (.CK (rc_gclk), .D (n_110), .Q (counter[8]));
  DFFQXL \counter_reg[9] (.CK (rc_gclk), .D (n_119), .Q (counter[9]));
  SDFFQX1 current_block_reg(.CK (rc_gclk_4699), .D (n_40), .SI (n_5),
       .SE (n_11), .Q (current_block));
  SDFFQX1 mode_reg(.CK (rc_gclk_4699), .D (n_4), .SI (n_138), .SE
       (n_87), .Q (n_139));
  DFFQXL \rd_counter_reg[0] (.CK (rc_gclk_4697), .D (n_21), .Q
       (rd_counter[0]));
  DFFQXL \rd_counter_reg[10] (.CK (rc_gclk_4697), .D (n_131), .Q
       (rd_counter[10]));
  DFFQXL \rd_counter_reg[11] (.CK (rc_gclk_4697), .D (n_137), .Q
       (rd_counter[11]));
  DFFQXL \rd_counter_reg[1] (.CK (rc_gclk_4697), .D (n_39), .Q
       (rd_counter[1]));
  DFFQXL \rd_counter_reg[2] (.CK (rc_gclk_4697), .D (n_50), .Q
       (rd_counter[2]));
  DFFQXL \rd_counter_reg[3] (.CK (rc_gclk_4697), .D (n_59), .Q
       (rd_counter[3]));
  DFFQXL \rd_counter_reg[4] (.CK (rc_gclk_4697), .D (n_69), .Q
       (rd_counter[4]));
  DFFQXL \rd_counter_reg[5] (.CK (rc_gclk_4697), .D (n_79), .Q
       (rd_counter[5]));
  DFFQXL \rd_counter_reg[6] (.CK (rc_gclk_4697), .D (n_90), .Q
       (rd_counter[6]));
  DFFQXL \rd_counter_reg[7] (.CK (rc_gclk_4697), .D (n_103), .Q
       (rd_counter[7]));
  DFFQXL \rd_counter_reg[8] (.CK (rc_gclk_4697), .D (n_112), .Q
       (rd_counter[8]));
  DFFQXL \rd_counter_reg[9] (.CK (rc_gclk_4697), .D (n_121), .Q
       (rd_counter[9]));
  DFFHQX1 \rom_counter_reg[0] (.CK (rc_gclk_4699), .D (n_20), .Q
       (rom_counter[0]));
  DFFQXL \rom_counter_reg[10] (.CK (rc_gclk_4699), .D (n_130), .Q
       (rom_counter[10]));
  DFFHQX1 \rom_counter_reg[11] (.CK (rc_gclk_4699), .D (n_136), .Q
       (rom_counter[11]));
  DFFQXL \rom_counter_reg[1] (.CK (rc_gclk_4699), .D (n_41), .Q
       (rom_counter[1]));
  DFFQXL \rom_counter_reg[2] (.CK (rc_gclk_4699), .D (n_49), .Q
       (rom_counter[2]));
  DFFQXL \rom_counter_reg[3] (.CK (rc_gclk_4699), .D (n_58), .Q
       (rom_counter[3]));
  DFFQXL \rom_counter_reg[4] (.CK (rc_gclk_4699), .D (n_68), .Q
       (rom_counter[4]));
  DFFQXL \rom_counter_reg[5] (.CK (rc_gclk_4699), .D (n_78), .Q
       (rom_counter[5]));
  DFFQXL \rom_counter_reg[6] (.CK (rc_gclk_4699), .D (n_89), .Q
       (rom_counter[6]));
  DFFQXL \rom_counter_reg[7] (.CK (rc_gclk_4699), .D (n_102), .Q
       (rom_counter[7]));
  DFFQXL \rom_counter_reg[8] (.CK (rc_gclk_4699), .D (n_111), .Q
       (rom_counter[8]));
  DFFQXL \rom_counter_reg[9] (.CK (rc_gclk_4699), .D (n_120), .Q
       (rom_counter[9]));
  EDFFHQX1 valid_reg(.CK (clk), .D (n_10), .E (n_205), .Q (n_140));
  NOR4BX1 g4430(.AN (counter[11]), .B (reset), .C (DevEn1), .D (n_128),
       .Y (n_138));
  NOR2X1 g4432(.A (n_6), .B (n_134), .Y (n_137));
  NOR2X1 g4433(.A (n_6), .B (n_133), .Y (n_136));
  NOR2X1 g4434(.A (n_13), .B (n_132), .Y (n_135));
  XNOR2X1 g4438(.A (rd_counter[11]), .B (n_124), .Y (n_134));
  XNOR2X1 g4439(.A (rom_counter[11]), .B (n_122), .Y (n_133));
  XNOR2X1 g4440(.A (counter[11]), .B (n_127), .Y (n_132));
  NOR2BX1 g4441(.AN (n_125), .B (n_6), .Y (n_131));
  NOR2BX1 g4442(.AN (n_123), .B (n_6), .Y (n_130));
  NOR2BX1 g4443(.AN (n_126), .B (n_1), .Y (n_129));
  NAND2X1 g4444(.A (n_268), .B (n_127), .Y (n_128));
  ADDHX1 g4445(.A (counter[10]), .B (n_115), .CO (n_127), .S (n_126));
  ADDHX1 g4446(.A (rd_counter[10]), .B (n_117), .CO (n_124), .S
       (n_125));
  ADDHX1 g4447(.A (rom_counter[10]), .B (n_113), .CO (n_122), .S
       (n_123));
  NOR2BX1 g4451(.AN (n_118), .B (n_8), .Y (n_121));
  NOR2BX1 g4452(.AN (n_114), .B (n_8), .Y (n_120));
  NOR2BX1 g4453(.AN (n_116), .B (n_13), .Y (n_119));
  ADDHX1 g4454(.A (rd_counter[9]), .B (n_108), .CO (n_117), .S (n_118));
  ADDHX1 g4455(.A (counter[9]), .B (n_106), .CO (n_115), .S (n_116));
  ADDHX1 g4456(.A (rom_counter[9]), .B (n_104), .CO (n_113), .S
       (n_114));
  NOR2BX1 g4460(.AN (n_109), .B (n_7), .Y (n_112));
  NOR2BX1 g4461(.AN (n_105), .B (n_8), .Y (n_111));
  NOR2BX1 g4462(.AN (n_107), .B (n_1), .Y (n_110));
  ADDHX1 g4463(.A (rd_counter[8]), .B (n_99), .CO (n_108), .S (n_109));
  ADDHX1 g4464(.A (counter[8]), .B (n_97), .CO (n_106), .S (n_107));
  ADDHX1 g4465(.A (rom_counter[8]), .B (n_95), .CO (n_104), .S (n_105));
  NOR2BX1 g4471(.AN (n_100), .B (n_8), .Y (n_103));
  NOR2BX1 g4472(.AN (n_96), .B (n_4), .Y (n_102));
  NOR2BX1 g4473(.AN (n_98), .B (n_13), .Y (n_101));
  ADDHX1 g4474(.A (rd_counter[7]), .B (n_85), .CO (n_99), .S (n_100));
  ADDHX1 g4475(.A (counter[7]), .B (n_83), .CO (n_97), .S (n_98));
  ADDHX1 g4476(.A (rom_counter[7]), .B (n_81), .CO (n_95), .S (n_96));
  OAI31X1 g4477(.A0 (n_80), .A1 (n_5), .A2 (n_29), .B0 (n_40), .Y
       (n_94));
  MXI2XL g4478(.A (n_274), .B (n_91), .S0 (n_5), .Y (n_93));
  NAND2BX1 g4481(.AN (n_91), .B (n_269), .Y (n_92));
  NOR2BX1 g4483(.AN (n_86), .B (n_6), .Y (n_90));
  NAND2BX1 g4484(.AN (n_80), .B (n_274), .Y (n_91));
  NOR2BX1 g4485(.AN (n_82), .B (n_7), .Y (n_89));
  NOR2BX1 g4486(.AN (n_84), .B (n_13), .Y (n_88));
  NAND2BX1 g4487(.AN (n_80), .B (n_277), .Y (n_87));
  ADDHX1 g4488(.A (rd_counter[6]), .B (n_73), .CO (n_85), .S (n_86));
  ADDHX1 g4489(.A (counter[6]), .B (n_71), .CO (n_83), .S (n_84));
  ADDHX1 g4490(.A (rom_counter[6]), .B (n_75), .CO (n_81), .S (n_82));
  AND4X1 g4491(.A (n_70), .B (counter[7]), .C (counter[8]), .D
       (counter[9]), .Y (n_80));
  NOR2BX1 g4495(.AN (n_74), .B (n_7), .Y (n_79));
  NOR2BX1 g4496(.AN (n_76), .B (n_8), .Y (n_78));
  NOR2BX1 g4497(.AN (n_72), .B (n_1), .Y (n_77));
  ADDHX1 g4498(.A (rom_counter[5]), .B (n_61), .CO (n_75), .S (n_76));
  ADDHX1 g4499(.A (rd_counter[5]), .B (n_63), .CO (n_73), .S (n_74));
  ADDHX1 g4500(.A (counter[5]), .B (n_65), .CO (n_71), .S (n_72));
  AND4XL g4501(.A (n_60), .B (counter[11]), .C (counter[5]), .D
       (counter[6]), .Y (n_70));
  NOR2BX1 g4505(.AN (n_64), .B (n_6), .Y (n_69));
  NOR2BX1 g4506(.AN (n_62), .B (n_7), .Y (n_68));
  NOR2BX1 g4507(.AN (n_66), .B (n_1), .Y (n_67));
  ADDHX1 g4508(.A (counter[4]), .B (n_56), .CO (n_65), .S (n_66));
  ADDHX1 g4509(.A (rd_counter[4]), .B (n_54), .CO (n_63), .S (n_64));
  ADDHX1 g4510(.A (rom_counter[4]), .B (n_52), .CO (n_61), .S (n_62));
  NOR4BBX1 g4511(.AN (counter[10]), .BN (n_56), .C (n_275), .D
       (DevEn1), .Y (n_60));
  NOR2BX1 g4515(.AN (n_55), .B (n_4), .Y (n_59));
  NOR2BX1 g4516(.AN (n_53), .B (n_4), .Y (n_58));
  NOR2BX1 g4517(.AN (n_51), .B (n_1), .Y (n_57));
  ADDHX1 g4518(.A (rd_counter[3]), .B (n_42), .CO (n_54), .S (n_55));
  ADDHX1 g4519(.A (rom_counter[3]), .B (n_44), .CO (n_52), .S (n_53));
  ADDHX1 g4520(.A (counter[3]), .B (n_46), .CO (n_56), .S (n_51));
  NOR2BX1 g4524(.AN (n_43), .B (n_8), .Y (n_50));
  NOR2BX1 g4526(.AN (n_45), .B (n_6), .Y (n_49));
  NOR2BX1 g4527(.AN (n_47), .B (n_13), .Y (n_48));
  ADDHX1 g4528(.A (counter[2]), .B (n_34), .CO (n_46), .S (n_47));
  ADDHX1 g4529(.A (rom_counter[2]), .B (n_30), .CO (n_44), .S (n_45));
  ADDHX1 g4530(.A (rd_counter[2]), .B (n_32), .CO (n_42), .S (n_43));
  OAI2BB1X1 g4536(.A0N (n_3), .A1N (n_31), .B0 (n_19), .Y (n_41));
  AND2X1 g4539(.A (n_33), .B (n_3), .Y (n_39));
  NAND2X1 g4541(.A (n_5), .B (n_29), .Y (n_40));
  AND2X1 g4542(.A (n_28), .B (n_6), .Y (n_38));
  NOR2BX1 g4543(.AN (n_35), .B (n_13), .Y (n_37));
  ADDHX1 g4545(.A (counter[1]), .B (counter[0]), .CO (n_34), .S (n_35));
  ADDHX1 g4546(.A (rd_counter[1]), .B (rd_counter[0]), .CO (n_32), .S
       (n_33));
  ADDHX1 g4547(.A (rom_counter[1]), .B (rom_counter[0]), .CO (n_30), .S
       (n_31));
  XNOR2X1 g4551(.A (Term_Counter[2]), .B (n_16), .Y (n_28));
  NOR2BX1 g4553(.AN (n_22), .B (Term_Counter[2]), .Y (n_29));
  NOR2BX1 g4555(.AN (n_268), .B (n_15), .Y (n_27));
  NOR2X1 g4556(.A (n_1), .B (counter[0]), .Y (n_26));
  NAND2BX1 g4557(.AN (n_15), .B (n_277), .Y (n_25));
  OA21X1 g4558(.A0 (n_4), .A1 (n_9), .B0 (n_277), .Y (n_24));
  OAI21X1 g4559(.A0 (rd_counter[0]), .A1 (mode), .B0 (n_19), .Y (n_21));
  MXI2XL g4560(.A (n_271), .B (rom_counter[0]), .S0 (n_3), .Y (n_20));
  NOR3BX1 g4561(.AN (n_270), .B (Term_Counter[0]), .C (n_3), .Y (n_23));
  NOR3BX1 g4562(.AN (Term_Counter[0]), .B (Term_Counter[1]), .C (n_3),
       .Y (n_22));
  OR2X1 g4563(.A (Dev1_State), .B (n_270), .Y (n_18));
  NAND2X1 g4564(.A (n_10), .B (n_5), .Y (n_17));
  OR2X1 g4565(.A (n_2), .B (n_270), .Y (n_19));
  NAND2X1 g4566(.A (Term_Counter[1]), .B (Term_Counter[0]), .Y (n_16));
  NOR2X1 g4567(.A (n_269), .B (n_5), .Y (n_15));
  NOR2X1 g4568(.A (n_3), .B (n_272), .Y (n_12));
  AND2X1 g4569(.A (n_274), .B (n_10), .Y (n_11));
  OR2X1 g4571(.A (reset), .B (mode), .Y (n_13));
  INVX1 g4572(.A (reset), .Y (n_10));
  INVX1 g4574(.A (n_5), .Y (n_9));
  BUFX2 g4576(.A (current_block), .Y (n_5));
  BUFX2 g4578(.A (n_4), .Y (n_8));
  BUFX2 g4580(.A (mode), .Y (n_4));
  INVX1 g4583(.A (n_2), .Y (n_7));
  INVX1 g4584(.A (n_2), .Y (n_6));
  INVX1 g4587(.A (mode), .Y (n_2));
  INVX1 g4589(.A (mode), .Y (n_3));
  BUFX12 drc_bufs4597(.A (n_139), .Y (mode));
  BUFX12 drc_bufs(.A (n_140), .Y (valid));
  INVX1 drc_bufs4599(.A (n_0), .Y (n_1));
  INVX1 drc_bufs4600(.A (n_13), .Y (n_0));
  AO21X1 g4604(.A0 (Term_Counter[1]), .A1 (n_23), .B0 (n_22), .Y
       (n_276));
  AOI21X1 g4605(.A0 (n_147), .A1 (n_205), .B0 (reset), .Y (n_277));
endmodule

