
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
// Generated on: May  6 2016 21:47:08

// Verification Directory fv/output_block 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_3(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_4(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module output_block(in, clk, reset, mode, validIn, out0, out1,
     validOut);
  input [3:0] in;
  input clk, reset, mode, validIn;
  output out0, out1, validOut;
  wire [3:0] in;
  wire clk, reset, mode, validIn;
  wire out0, out1, validOut;
  wire [3:0] RdIndex;
  wire [15:0] buffer0;
  wire [15:0] buffer1;
  wire [4:0] counter;
  wire [3:0] WrIndex0;
  wire [3:0] WrIndex1;
  wire [1:0] counter2;
  wire RdStart, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13;
  wire UNCONNECTED14, UNCONNECTED15, UNCONNECTED16, UNCONNECTED17,
       current_buf, n_0, n_1, n_2;
  wire n_4, n_5, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_67, n_68, n_69, n_71, n_73;
  wire n_74, n_75, n_77, n_79, n_84, n_86, n_87, n_88;
  wire n_89, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_103, n_104, n_105, n_106;
  wire n_107, n_111, n_114, n_116, n_119, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_139, n_140;
  wire n_142, n_143, n_144, n_145, n_146, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_164, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_181, n_182, n_183, n_188, n_189, n_190;
  wire n_191, n_193, n_194, n_195, n_196, n_199, n_200, n_202;
  wire n_207, n_208, n_212, n_213, n_215, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_242, n_243, n_244, n_245, n_247, n_249, n_250;
  wire n_252, n_253, n_254, n_255, n_256, n_257, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_266, n_267;
  wire n_268, n_269, n_270, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_281, n_282, n_284, n_285, n_286;
  wire n_287, n_288, n_289, n_290, n_291, n_292, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_300, n_303, n_304, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315, n_316, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_346, n_347, n_348;
  wire n_349, n_350, n_351, n_352, n_353, n_354, n_355, n_356;
  wire n_357, n_358, n_359, n_360, n_361, n_362, n_363, n_364;
  wire n_365, n_366, n_367, n_368, n_369, n_370, n_371, n_372;
  wire n_373, n_374, n_375, n_377, n_380, n_382, n_383, n_384;
  wire n_385, n_386, n_387, n_388, n_389, n_390, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_415, n_423, n_425;
  wire n_426, n_427, n_428, n_429, n_430, n_431, n_432, n_433;
  wire n_434, n_435, n_436, n_439, n_441, n_442, n_444, n_445;
  wire n_446, n_447, n_448, n_449, n_450, n_451, n_452, n_453;
  wire n_454, n_455, n_456, n_457, n_458, n_459, n_460, n_461;
  wire n_462, n_463, n_464, n_466, n_467, n_468, n_469, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_478;
  wire n_479, n_480, n_481, n_482, n_483, n_484, n_485, n_486;
  wire n_487, n_488, n_489, n_490, n_491, n_492, n_493, n_494;
  wire n_495, n_496, n_497, n_498, n_499, n_561, n_562, n_563;
  wire n_564, n_565, n_566, n_567, n_569, n_570, n_571, n_572;
  wire n_575, n_576, n_577, n_578, n_580, n_581, n_582, n_590;
  wire n_592, n_593, n_594, n_596, n_597, n_598, n_599, n_601;
  wire n_662, n_673, n_684, n_706, n_744, n_751, n_752, n_753;
  wire n_754, n_755, n_756, n_757, n_758, n_759, n_760, n_761;
  wire n_762, n_763, n_764, n_765, n_766, n_767, n_768, n_769;
  wire n_770, n_771, n_772, n_775, n_776, n_777, n_779, n_780;
  wire n_781, n_782, n_783, n_784, n_785, n_786, rc_gclk, rc_gclk_6717;
  wire rc_gclk_6720, rc_gclk_6722, rc_gclk_6725;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_566), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_565), .ck_in (clk), .ck_out
       (rc_gclk_6717), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_564), .ck_in (clk), .ck_out
       (rc_gclk_6720), .test (1'b0));
  RC_CG_MOD_3 RC_CG_HIER_INST3(.enable (n_476), .ck_in (clk), .ck_out
       (rc_gclk_6722), .test (1'b0));
  RC_CG_MOD_4 RC_CG_HIER_INST4(.enable (n_563), .ck_in (clk), .ck_out
       (rc_gclk_6725), .test (1'b0));
  INVX2 g5516(.A (n_590), .Y (n_499));
  SDFFQX1 out0_reg(.CK (rc_gclk_6722), .D (n_491), .SI (n_490), .SE
       (RdIndex[3]), .Q (n_496));
  DFFRX1 out0_reg734(.RN (1'b1), .CK (clk), .D (n_684), .Q
       (UNCONNECTED), .QN (n_498));
  SDFFQX1 out1_reg(.CK (rc_gclk_6722), .D (n_489), .SI (n_488), .SE
       (RdIndex[3]), .Q (n_495));
  DFFRX1 out1_reg735(.RN (1'b1), .CK (clk), .D (n_684), .Q
       (UNCONNECTED0), .QN (n_497));
  DFFRX1 validOut_reg(.RN (1'b1), .CK (rc_gclk_6722), .D (n_484), .Q
       (UNCONNECTED1), .QN (n_493));
  TBUFX12 out0_tri(.A (n_496), .OE (n_498), .Y (out0));
  TBUFX12 out1_tri(.A (n_495), .OE (n_497), .Y (out1));
  OR4X1 g6555(.A (n_673), .B (n_494), .C (n_571), .D (n_576), .Y
       (n_565));
  AOI21X1 g6556(.A0 (n_492), .A1 (n_572), .B0 (current_buf), .Y
       (n_494));
  NAND2X1 g6557(.A (n_477), .B (n_487), .Y (n_564));
  INVX12 g6559(.A (n_493), .Y (validOut));
  OAI21X1 g6560(.A0 (n_599), .A1 (n_581), .B0 (n_439), .Y (n_492));
  NAND2X1 g6561(.A (n_486), .B (n_485), .Y (n_491));
  NAND2X1 g6562(.A (n_478), .B (n_481), .Y (n_490));
  NAND2X1 g6563(.A (n_479), .B (n_480), .Y (n_489));
  NAND2X1 g6564(.A (n_483), .B (n_482), .Y (n_488));
  AOI211X1 g6565(.A0 (n_744), .A1 (n_581), .B0 (n_673), .C0 (n_580), .Y
       (n_487));
  AOI221X1 g6566(.A0 (buffer0[0]), .A1 (n_433), .B0 (buffer0[3]), .B1
       (n_463), .C0 (n_473), .Y (n_486));
  AOI221X1 g6567(.A0 (buffer0[1]), .A1 (n_435), .B0 (buffer0[2]), .B1
       (n_434), .C0 (n_470), .Y (n_485));
  NOR2BX1 g6568(.AN (n_476), .B (n_684), .Y (n_484));
  AOI221X1 g6569(.A0 (buffer1[10]), .A1 (n_434), .B0 (buffer1[14]), .B1
       (n_459), .C0 (n_472), .Y (n_483));
  AOI221X1 g6570(.A0 (buffer1[8]), .A1 (n_433), .B0 (buffer1[11]), .B1
       (n_463), .C0 (n_471), .Y (n_482));
  AOI221X1 g6571(.A0 (buffer0[13]), .A1 (n_458), .B0 (buffer0[14]), .B1
       (n_459), .C0 (n_468), .Y (n_481));
  AOI221X1 g6572(.A0 (buffer1[5]), .A1 (n_458), .B0 (buffer1[3]), .B1
       (n_463), .C0 (n_469), .Y (n_480));
  AOI221X1 g6573(.A0 (buffer1[2]), .A1 (n_434), .B0 (buffer1[6]), .B1
       (n_459), .C0 (n_474), .Y (n_479));
  AOI221X1 g6574(.A0 (buffer0[8]), .A1 (n_433), .B0 (buffer0[11]), .B1
       (n_463), .C0 (n_467), .Y (n_478));
  AOI21X1 g6575(.A0 (current_buf), .A1 (n_582), .B0 (n_590), .Y
       (n_477));
  INVX1 g6576(.A (n_475), .Y (n_566));
  AOI31X1 g6577(.A0 (counter[0]), .A1 (n_448), .A2 (n_453), .B0
       (n_577), .Y (n_475));
  NOR2BX2 g6578(.AN (n_569), .B (n_461), .Y (n_580));
  NAND2X2 g6579(.A (n_562), .B (n_561), .Y (n_572));
  NOR2X1 g6580(.A (n_461), .B (n_432), .Y (n_576));
  NOR2X4 g6581(.A (n_456), .B (n_466), .Y (n_590));
  OAI31X1 g6582(.A0 (n_0), .A1 (n_449), .A2 (n_454), .B0 (n_445), .Y
       (n_476));
  NOR2X6 g6583(.A (n_457), .B (n_68), .Y (n_571));
  NOR2X1 g6584(.A (n_436), .B (n_466), .Y (n_581));
  AO22X1 g6585(.A0 (buffer1[4]), .A1 (n_462), .B0 (buffer1[7]), .B1
       (n_464), .Y (n_474));
  AO22X1 g6586(.A0 (buffer0[4]), .A1 (n_462), .B0 (buffer0[7]), .B1
       (n_464), .Y (n_473));
  AO22X1 g6587(.A0 (buffer1[9]), .A1 (n_435), .B0 (buffer1[13]), .B1
       (n_458), .Y (n_472));
  AO22X1 g6588(.A0 (buffer1[12]), .A1 (n_462), .B0 (buffer1[15]), .B1
       (n_464), .Y (n_471));
  AO22X1 g6589(.A0 (buffer0[5]), .A1 (n_458), .B0 (buffer0[6]), .B1
       (n_459), .Y (n_470));
  AO22X1 g6590(.A0 (buffer1[0]), .A1 (n_433), .B0 (buffer1[1]), .B1
       (n_435), .Y (n_469));
  AO22X1 g6591(.A0 (buffer0[9]), .A1 (n_435), .B0 (buffer0[10]), .B1
       (n_434), .Y (n_468));
  AO22X1 g6592(.A0 (buffer0[12]), .A1 (n_462), .B0 (buffer0[15]), .B1
       (n_464), .Y (n_467));
  INVX2 g6593(.A (n_561), .Y (n_466));
  NAND2X4 g6594(.A (counter[1]), .B (n_460), .Y (n_432));
  NOR2X8 g6595(.A (counter[0]), .B (n_570), .Y (n_561));
  INVX3 g6596(.A (n_569), .Y (n_68));
  NOR3X6 g6598(.A (counter[1]), .B (n_451), .C (n_452), .Y (n_569));
  OR2X1 g6600(.A (n_673), .B (counter[0]), .Y (n_563));
  NOR2BX1 g6602(.AN (RdIndex[2]), .B (n_455), .Y (n_464));
  NOR2X2 g6603(.A (RdIndex[2]), .B (n_455), .Y (n_463));
  AND2X1 g6605(.A (n_446), .B (n_662), .Y (n_462));
  INVX8 g6606(.A (n_460), .Y (n_570));
  NAND2X4 g6607(.A (n_575), .B (n_26), .Y (n_457));
  NAND2X2 g6608(.A (n_444), .B (current_buf), .Y (n_456));
  NAND2X2 g6609(.A (n_0), .B (n_575), .Y (n_461));
  NOR2X8 g6612(.A (n_451), .B (n_452), .Y (n_460));
  AND2X1 g6613(.A (RdIndex[2]), .B (n_447), .Y (n_459));
  AND2X1 g6614(.A (n_450), .B (n_662), .Y (n_458));
  INVX1 g6615(.A (n_453), .Y (n_454));
  NOR2X2 g6618(.A (mode), .B (current_buf), .Y (n_567));
  NAND2X1 g6619(.A (RdIndex[0]), .B (RdIndex[1]), .Y (n_455));
  NAND2X1 g6620(.A (counter[3]), .B (counter[4]), .Y (n_453));
  NOR2X6 g6621(.A (counter[2]), .B (n_442), .Y (n_452));
  NOR2X6 g6622(.A (counter[3]), .B (n_441), .Y (n_451));
  NOR2BX1 g6623(.AN (RdIndex[0]), .B (RdIndex[1]), .Y (n_450));
  NOR2X4 g6624(.A (counter[1]), .B (counter[4]), .Y (n_562));
  INVX1 g6625(.A (n_448), .Y (n_449));
  INVX1 g6630(.A (n_577), .Y (n_445));
  NOR2X1 g6631(.A (mode), .B (counter[4]), .Y (n_444));
  NOR2X1 g6632(.A (n_441), .B (counter[1]), .Y (n_448));
  NAND2X4 g6633(.A (counter[1]), .B (n_62), .Y (n_436));
  NOR2BX1 g6634(.AN (RdIndex[1]), .B (RdIndex[0]), .Y (n_447));
  NOR2X1 g6635(.A (RdIndex[0]), .B (RdIndex[1]), .Y (n_446));
  NOR2X4 g6636(.A (n_439), .B (counter[4]), .Y (n_575));
  OR2X1 g6637(.A (reset), .B (n_60), .Y (n_578));
  INVX4 g6641(.A (counter[3]), .Y (n_442));
  INVX6 g6642(.A (counter[2]), .Y (n_441));
  INVX3 g6643(.A (counter[4]), .Y (n_62));
  INVX1 g6644(.A (mode), .Y (n_439));
  NOR2BX1 g2(.AN (n_450), .B (RdIndex[2]), .Y (n_435));
  NOR3BX1 g6659(.AN (n_562), .B (n_26), .C (n_570), .Y (n_582));
  NOR2BX1 g6660(.AN (n_447), .B (n_662), .Y (n_434));
  NOR2BX1 g6661(.AN (n_446), .B (n_662), .Y (n_433));
  NAND2BX2 g6662(.AN (reset), .B (RdStart), .Y (n_577));
  DFFHQX1 \RdIndex_reg[0] (.CK (rc_gclk), .D (n_79), .Q (RdIndex[0]));
  DFFHQX1 \RdIndex_reg[1] (.CK (rc_gclk), .D (n_191), .Q (RdIndex[1]));
  DFFHQX1 \RdIndex_reg[2] (.CK (rc_gclk), .D (n_243), .Q (RdIndex[2]));
  DFFQXL \RdIndex_reg[3] (.CK (rc_gclk), .D (n_308), .Q (RdIndex[3]));
  SDFFQX1 RdStart_reg(.CK (rc_gclk_6725), .D (n_63), .SI (RdStart), .SE
       (n_269), .Q (RdStart));
  DFFHQX1 \WrIndex0_reg[0] (.CK (rc_gclk_6717), .D (n_415), .Q
       (WrIndex0[0]));
  DFFQXL \WrIndex1_reg[1] (.CK (rc_gclk_6720), .D (n_400), .Q
       (WrIndex1[1]));
  DFFTRXL \buffer0_reg[0] (.CK (clk), .D (n_760), .RN (n_18), .Q
       (buffer0[0]), .QN (UNCONNECTED2));
  DFFTRXL \buffer0_reg[10] (.CK (clk), .D (n_753), .RN (n_17), .Q
       (buffer0[10]), .QN (UNCONNECTED3));
  DFFTRXL \buffer0_reg[11] (.CK (clk), .D (n_755), .RN (n_17), .Q
       (buffer0[11]), .QN (UNCONNECTED4));
  DFFTRXL \buffer0_reg[12] (.CK (clk), .D (n_761), .RN (n_16), .Q
       (buffer0[12]), .QN (UNCONNECTED5));
  DFFTRXL \buffer0_reg[13] (.CK (clk), .D (n_762), .RN (n_17), .Q
       (buffer0[13]), .QN (UNCONNECTED6));
  DFFTRXL \buffer0_reg[14] (.CK (clk), .D (n_763), .RN (n_17), .Q
       (buffer0[14]), .QN (UNCONNECTED7));
  DFFTRXL \buffer0_reg[15] (.CK (clk), .D (n_764), .RN (n_16), .Q
       (buffer0[15]), .QN (UNCONNECTED8));
  DFFTRXL \buffer0_reg[1] (.CK (clk), .D (n_757), .RN (n_18), .Q
       (buffer0[1]), .QN (UNCONNECTED9));
  DFFTRXL \buffer0_reg[2] (.CK (clk), .D (n_758), .RN (n_15), .Q
       (buffer0[2]), .QN (UNCONNECTED10));
  DFFTRXL \buffer0_reg[3] (.CK (clk), .D (n_754), .RN (n_18), .Q
       (buffer0[3]), .QN (UNCONNECTED11));
  DFFTRXL \buffer0_reg[4] (.CK (clk), .D (n_765), .RN (n_16), .Q
       (buffer0[4]), .QN (UNCONNECTED12));
  DFFTRXL \buffer0_reg[5] (.CK (clk), .D (n_766), .RN (n_18), .Q
       (buffer0[5]), .QN (UNCONNECTED13));
  DFFTRXL \buffer0_reg[6] (.CK (clk), .D (n_767), .RN (n_15), .Q
       (buffer0[6]), .QN (UNCONNECTED14));
  DFFTRXL \buffer0_reg[7] (.CK (clk), .D (n_756), .RN (n_15), .Q
       (buffer0[7]), .QN (UNCONNECTED15));
  DFFTRXL \buffer0_reg[8] (.CK (clk), .D (n_768), .RN (n_16), .Q
       (buffer0[8]), .QN (UNCONNECTED16));
  DFFTRXL \buffer0_reg[9] (.CK (clk), .D (n_759), .RN (n_18), .Q
       (buffer0[9]), .QN (UNCONNECTED17));
  DFFTRXL \buffer1_reg[0] (.CK (clk), .D (n_371), .RN (n_16), .Q
       (buffer1[0]), .QN (n_42));
  DFFTRXL \buffer1_reg[10] (.CK (clk), .D (n_361), .RN (n_16), .Q
       (buffer1[10]), .QN (n_43));
  DFFTRXL \buffer1_reg[11] (.CK (clk), .D (n_370), .RN (n_17), .Q
       (buffer1[11]), .QN (n_32));
  DFFTRXL \buffer1_reg[12] (.CK (clk), .D (n_359), .RN (n_16), .Q
       (buffer1[12]), .QN (n_33));
  DFFTRXL \buffer1_reg[13] (.CK (clk), .D (n_358), .RN (n_15), .Q
       (buffer1[13]), .QN (n_46));
  DFFTRXL \buffer1_reg[14] (.CK (clk), .D (n_357), .RN (n_15), .Q
       (buffer1[14]), .QN (n_31));
  DFFTRXL \buffer1_reg[15] (.CK (clk), .D (n_369), .RN (n_15), .Q
       (buffer1[15]), .QN (n_34));
  DFFTRXL \buffer1_reg[1] (.CK (clk), .D (n_368), .RN (n_18), .Q
       (buffer1[1]), .QN (n_35));
  DFFTRXL \buffer1_reg[2] (.CK (clk), .D (n_367), .RN (n_17), .Q
       (buffer1[2]), .QN (n_30));
  DFFTRXL \buffer1_reg[3] (.CK (clk), .D (n_366), .RN (n_17), .Q
       (buffer1[3]), .QN (n_50));
  DFFTRXL \buffer1_reg[4] (.CK (clk), .D (n_365), .RN (n_17), .Q
       (buffer1[4]), .QN (n_47));
  DFFTRXL \buffer1_reg[5] (.CK (clk), .D (n_364), .RN (n_16), .Q
       (buffer1[5]), .QN (n_44));
  DFFTRXL \buffer1_reg[6] (.CK (clk), .D (n_363), .RN (n_15), .Q
       (buffer1[6]), .QN (n_48));
  DFFTRXL \buffer1_reg[7] (.CK (clk), .D (n_362), .RN (n_15), .Q
       (buffer1[7]), .QN (n_45));
  DFFTRXL \buffer1_reg[8] (.CK (clk), .D (n_360), .RN (n_18), .Q
       (buffer1[8]), .QN (n_36));
  DFFTRXL \buffer1_reg[9] (.CK (clk), .D (n_356), .RN (n_18), .Q
       (buffer1[9]), .QN (n_49));
  DFFHQX1 \counter2_reg[0] (.CK (clk), .D (n_194), .Q (counter2[0]));
  DFFHQX1 \counter2_reg[1] (.CK (clk), .D (n_245), .Q (counter2[1]));
  DFFHQX4 \counter_reg[1] (.CK (rc_gclk_6725), .D (n_196), .Q
       (counter[1]));
  DFFHQX4 \counter_reg[2] (.CK (rc_gclk_6725), .D (n_244), .Q
       (counter[2]));
  DFFQX4 \counter_reg[4] (.CK (rc_gclk_6725), .D (n_306), .Q
       (counter[4]));
  DFFQX2 current_buf_reg(.CK (clk), .D (n_235), .Q (current_buf));
  NOR2X1 g9227(.A (n_11), .B (n_427), .Y (n_431));
  NOR2X1 g9228(.A (n_67), .B (n_428), .Y (n_430));
  AOI31X1 g9239(.A0 (n_374), .A1 (n_771), .A2 (n_769), .B0 (n_67), .Y
       (n_429));
  AOI21X2 g9240(.A0 (WrIndex0[2]), .A1 (n_423), .B0 (n_425), .Y
       (n_428));
  AOI221X2 g9241(.A0 (WrIndex0[3]), .A1 (n_392), .B0 (n_394), .B1
       (n_87), .C0 (n_783), .Y (n_427));
  NOR2X1 g9250(.A (n_67), .B (n_406), .Y (n_426));
  AOI21X1 g9251(.A0 (n_249), .A1 (n_393), .B0 (WrIndex0[2]), .Y
       (n_425));
  NAND2X1 g9272(.A (n_160), .B (n_770), .Y (n_423));
  NOR2X1 g9280(.A (n_67), .B (n_382), .Y (n_415));
  MX2X1 g9289(.A (n_316), .B (n_373), .S0 (WrIndex1[2]), .Y (n_406));
  NOR2X1 g9290(.A (n_67), .B (n_375), .Y (n_405));
  OAI21X2 g9291(.A0 (n_324), .A1 (n_346), .B0 (n_21), .Y (n_404));
  OAI21X2 g9292(.A0 (n_323), .A1 (n_345), .B0 (n_57), .Y (n_403));
  OAI21X2 g9293(.A0 (n_322), .A1 (n_355), .B0 (n_21), .Y (n_402));
  OAI21X2 g9294(.A0 (n_334), .A1 (n_344), .B0 (n_13), .Y (n_401));
  NOR2X1 g9295(.A (n_11), .B (n_372), .Y (n_400));
  OAI21X2 g9296(.A0 (n_328), .A1 (n_352), .B0 (n_57), .Y (n_399));
  OAI21X2 g9297(.A0 (n_321), .A1 (n_341), .B0 (n_13), .Y (n_398));
  OAI21X2 g9298(.A0 (n_333), .A1 (n_337), .B0 (n_57), .Y (n_397));
  OAI21X2 g9299(.A0 (n_332), .A1 (n_353), .B0 (n_13), .Y (n_396));
  NOR2X1 g9300(.A (n_67), .B (n_380), .Y (n_395));
  INVX1 g9301(.A (n_393), .Y (n_394));
  INVX2 g9302(.A (n_770), .Y (n_392));
  OAI21X2 g9303(.A0 (n_320), .A1 (n_340), .B0 (n_13), .Y (n_390));
  OAI21X2 g9304(.A0 (n_330), .A1 (n_342), .B0 (n_57), .Y (n_389));
  OAI21X2 g9305(.A0 (n_327), .A1 (n_351), .B0 (n_54), .Y (n_388));
  OAI21X2 g9306(.A0 (n_326), .A1 (n_348), .B0 (n_13), .Y (n_387));
  OAI21X2 g9307(.A0 (n_336), .A1 (n_347), .B0 (n_13), .Y (n_386));
  OAI21X2 g9308(.A0 (n_329), .A1 (n_338), .B0 (n_57), .Y (n_385));
  OAI21X2 g9309(.A0 (n_331), .A1 (n_343), .B0 (n_57), .Y (n_384));
  OAI21X2 g9310(.A0 (n_319), .A1 (n_339), .B0 (n_21), .Y (n_383));
  MX2X1 g9311(.A (n_349), .B (n_7), .S0 (WrIndex0[0]), .Y (n_382));
  NOR2X2 g9313(.A (n_752), .B (n_377), .Y (n_393));
  MX2X1 g9315(.A (n_268), .B (n_238), .S0 (WrIndex1[0]), .Y (n_380));
  AOI2BB1X4 g9318(.A0N (n_199), .A1N (n_314), .B0 (n_95), .Y (n_377));
  AOI221X1 g9320(.A0 (n_168), .A1 (n_199), .B0 (n_129), .B1 (n_314),
       .C0 (n_592), .Y (n_375));
  OAI2BB1X1 g9321(.A0N (n_300), .A1N (n_234), .B0 (WrIndex1[2]), .Y
       (n_374));
  AOI222X1 g9322(.A0 (n_123), .A1 (n_208), .B0 (n_38), .B1 (n_237), .C0
       (n_202), .C1 (n_284), .Y (n_373));
  AOI221X1 g9323(.A0 (n_150), .A1 (n_208), .B0 (n_298), .B1 (n_202),
       .C0 (n_281), .Y (n_372));
  OAI21X1 g9324(.A0 (n_19), .A1 (n_297), .B0 (n_77), .Y (n_371));
  OAI21X1 g9325(.A0 (n_58), .A1 (n_295), .B0 (n_107), .Y (n_370));
  OAI21X1 g9326(.A0 (n_58), .A1 (n_294), .B0 (n_69), .Y (n_369));
  MXI2X1 g9328(.A (n_293), .B (n_35), .S0 (n_19), .Y (n_368));
  OAI21X1 g9329(.A0 (n_19), .A1 (n_292), .B0 (n_111), .Y (n_367));
  MXI2X1 g9330(.A (n_291), .B (n_50), .S0 (n_56), .Y (n_366));
  MXI2X1 g9331(.A (n_290), .B (n_47), .S0 (n_19), .Y (n_365));
  MXI2X1 g9332(.A (n_289), .B (n_44), .S0 (n_56), .Y (n_364));
  OAI21X1 g9333(.A0 (n_56), .A1 (n_288), .B0 (n_84), .Y (n_363));
  MXI2X1 g9334(.A (n_287), .B (n_45), .S0 (n_56), .Y (n_362));
  OAI21X1 g9335(.A0 (n_19), .A1 (n_296), .B0 (n_105), .Y (n_361));
  OAI21X1 g9336(.A0 (n_19), .A1 (n_286), .B0 (n_74), .Y (n_360));
  OAI2BB1X1 g9337(.A0N (n_19), .A1N (buffer1[12]), .B0 (n_325), .Y
       (n_359));
  OAI2BB1X1 g9338(.A0N (n_56), .A1N (buffer1[13]), .B0 (n_350), .Y
       (n_358));
  OAI2BB1X1 g9339(.A0N (n_56), .A1N (buffer1[14]), .B0 (n_335), .Y
       (n_357));
  OAI2BB1X1 g9340(.A0N (n_56), .A1N (buffer1[9]), .B0 (n_354), .Y
       (n_356));
  NOR2X4 g9341(.A (n_52), .B (n_310), .Y (n_355));
  OAI21X1 g9342(.A0 (n_751), .A1 (n_258), .B0 (n_21), .Y (n_354));
  NOR2X4 g9343(.A (n_88), .B (n_313), .Y (n_353));
  NOR2X4 g9344(.A (n_91), .B (n_311), .Y (n_352));
  NOR2X4 g9345(.A (n_91), .B (n_312), .Y (n_351));
  OAI21X1 g9346(.A0 (n_247), .A1 (n_260), .B0 (n_21), .Y (n_350));
  NOR2X1 g9347(.A (n_314), .B (n_199), .Y (n_349));
  NOR2X4 g9348(.A (n_51), .B (n_311), .Y (n_348));
  NOR2X4 g9349(.A (n_91), .B (n_310), .Y (n_347));
  NOR2X4 g9350(.A (n_52), .B (n_311), .Y (n_346));
  NOR2X4 g9351(.A (n_52), .B (n_312), .Y (n_345));
  NOR2X4 g9352(.A (n_51), .B (n_313), .Y (n_344));
  NOR2X4 g9353(.A (n_51), .B (n_312), .Y (n_343));
  NOR2X4 g9354(.A (n_51), .B (n_310), .Y (n_342));
  NOR2X4 g9355(.A (n_88), .B (n_311), .Y (n_341));
  NOR2X4 g9356(.A (n_88), .B (n_312), .Y (n_340));
  NOR2X4 g9357(.A (n_88), .B (n_310), .Y (n_339));
  NOR2X4 g9358(.A (n_52), .B (n_313), .Y (n_338));
  NOR2X4 g9359(.A (n_91), .B (n_313), .Y (n_337));
  OA21X1 g9363(.A0 (n_12), .A1 (n_276), .B0 (buffer0[10]), .Y (n_336));
  OAI21X2 g9364(.A0 (n_5), .A1 (n_256), .B0 (n_22), .Y (n_335));
  OA21X1 g9365(.A0 (n_51), .A1 (n_277), .B0 (buffer0[3]), .Y (n_334));
  OA21X1 g9366(.A0 (n_91), .A1 (n_277), .B0 (buffer0[11]), .Y (n_333));
  OA21X1 g9367(.A0 (n_10), .A1 (n_277), .B0 (buffer0[7]), .Y (n_332));
  OA21X1 g9368(.A0 (n_89), .A1 (n_279), .B0 (buffer0[1]), .Y (n_331));
  OA21X1 g9369(.A0 (n_51), .A1 (n_276), .B0 (buffer0[2]), .Y (n_330));
  OA21X1 g9370(.A0 (n_52), .A1 (n_277), .B0 (buffer0[15]), .Y (n_329));
  OA21X1 g9371(.A0 (n_12), .A1 (n_278), .B0 (buffer0[8]), .Y (n_328));
  OA21X1 g9372(.A0 (n_91), .A1 (n_279), .B0 (buffer0[9]), .Y (n_327));
  OA21X1 g9373(.A0 (n_89), .A1 (n_278), .B0 (buffer0[0]), .Y (n_326));
  OAI21X2 g9374(.A0 (n_236), .A1 (n_261), .B0 (n_21), .Y (n_325));
  OA21X1 g9375(.A0 (n_52), .A1 (n_278), .B0 (buffer0[12]), .Y (n_324));
  OA21X1 g9376(.A0 (n_52), .A1 (n_279), .B0 (buffer0[13]), .Y (n_323));
  OA21X1 g9377(.A0 (n_52), .A1 (n_276), .B0 (buffer0[14]), .Y (n_322));
  OA21X1 g9378(.A0 (n_88), .A1 (n_278), .B0 (buffer0[4]), .Y (n_321));
  OA21X1 g9379(.A0 (n_10), .A1 (n_279), .B0 (buffer0[5]), .Y (n_320));
  OA21X1 g9380(.A0 (n_88), .A1 (n_276), .B0 (buffer0[6]), .Y (n_319));
  AOI2BB1X1 g9383(.A0N (n_127), .A1N (n_268), .B0 (n_304), .Y (n_316));
  OAI31X1 g9384(.A0 (n_175), .A1 (n_131), .A2 (n_8), .B0 (n_303), .Y
       (n_315));
  AOI2BB1X1 g9385(.A0N (n_51), .A1N (n_249), .B0 (n_255), .Y (n_309));
  NOR2X1 g9386(.A (n_684), .B (n_253), .Y (n_308));
  NOR2X1 g9387(.A (n_673), .B (n_250), .Y (n_307));
  NOR2X1 g9388(.A (n_578), .B (n_252), .Y (n_306));
  AO21X1 g9390(.A0 (n_122), .A1 (n_208), .B0 (n_281), .Y (n_304));
  NAND2X1 g9391(.A (n_104), .B (n_281), .Y (n_303));
  NAND2X1 g9394(.A (n_151), .B (n_267), .Y (n_300));
  NOR2X2 g9396(.A (n_24), .B (n_282), .Y (n_314));
  OR2X6 g9397(.A (n_95), .B (n_786), .Y (n_313));
  OR2X6 g9398(.A (n_99), .B (n_786), .Y (n_312));
  OR2X6 g9399(.A (n_92), .B (n_786), .Y (n_311));
  OR2X6 g9400(.A (n_128), .B (n_786), .Y (n_310));
  OAI22X1 g9401(.A0 (n_124), .A1 (n_8), .B0 (n_24), .B1 (n_133), .Y
       (n_298));
  AOI21X2 g9402(.A0 (n_159), .A1 (n_224), .B0 (n_274), .Y (n_297));
  AOI21X2 g9403(.A0 (n_154), .A1 (n_224), .B0 (n_262), .Y (n_296));
  AOI21X2 g9404(.A0 (n_157), .A1 (n_224), .B0 (n_263), .Y (n_295));
  AOI21X2 g9405(.A0 (n_157), .A1 (n_228), .B0 (n_259), .Y (n_294));
  AOI21X2 g9406(.A0 (n_158), .A1 (n_224), .B0 (n_270), .Y (n_293));
  AOI21X2 g9407(.A0 (n_156), .A1 (n_224), .B0 (n_272), .Y (n_292));
  AOI21X2 g9408(.A0 (n_151), .A1 (n_224), .B0 (n_257), .Y (n_291));
  AOI21X2 g9409(.A0 (n_159), .A1 (n_228), .B0 (n_265), .Y (n_290));
  AOI21X2 g9410(.A0 (n_158), .A1 (n_228), .B0 (n_273), .Y (n_289));
  AOI21X2 g9411(.A0 (n_156), .A1 (n_228), .B0 (n_275), .Y (n_288));
  AOI21X2 g9412(.A0 (n_151), .A1 (n_228), .B0 (n_264), .Y (n_287));
  AOI21X2 g9413(.A0 (n_152), .A1 (n_224), .B0 (n_266), .Y (n_286));
  OAI22X1 g9414(.A0 (n_177), .A1 (n_8), .B0 (n_73), .B1 (n_175), .Y
       (n_285));
  OAI22X1 g9415(.A0 (n_38), .A1 (n_8), .B0 (n_24), .B1 (n_124), .Y
       (n_284));
  AOI21X2 g9417(.A0 (n_156), .A1 (n_226), .B0 (n_48), .Y (n_275));
  AOI21X2 g9418(.A0 (n_159), .A1 (n_222), .B0 (n_42), .Y (n_274));
  AOI21X2 g9419(.A0 (n_158), .A1 (n_226), .B0 (n_44), .Y (n_273));
  AOI21X2 g9420(.A0 (n_156), .A1 (n_222), .B0 (n_30), .Y (n_272));
  AOI21X2 g9422(.A0 (n_158), .A1 (n_222), .B0 (n_35), .Y (n_270));
  NOR2X2 g9423(.A (n_179), .B (n_593), .Y (n_282));
  AOI31X1 g9424(.A0 (n_41), .A1 (n_706), .A2 (n_230), .B0 (n_578), .Y
       (n_269));
  NOR2X2 g9425(.A (n_38), .B (n_238), .Y (n_281));
  OR2X2 g9430(.A (n_99), .B (n_240), .Y (n_279));
  OR2X2 g9431(.A (n_92), .B (n_240), .Y (n_278));
  OR2X2 g9432(.A (n_95), .B (n_240), .Y (n_277));
  NAND2X2 g9433(.A (n_129), .B (n_239), .Y (n_276));
  INVX1 g9435(.A (n_267), .Y (n_268));
  AOI21X2 g9436(.A0 (n_152), .A1 (n_222), .B0 (n_36), .Y (n_266));
  AOI21X2 g9437(.A0 (n_159), .A1 (n_226), .B0 (n_47), .Y (n_265));
  AOI21X2 g9438(.A0 (n_151), .A1 (n_226), .B0 (n_45), .Y (n_264));
  AOI21X2 g9439(.A0 (n_157), .A1 (n_222), .B0 (n_32), .Y (n_263));
  AOI21X2 g9440(.A0 (n_154), .A1 (n_222), .B0 (n_43), .Y (n_262));
  AOI21X2 g9441(.A0 (n_152), .A1 (n_226), .B0 (n_33), .Y (n_261));
  AOI2BB1X1 g9442(.A0N (n_155), .A1N (n_225), .B0 (n_46), .Y (n_260));
  AOI21X2 g9443(.A0 (n_157), .A1 (n_226), .B0 (n_34), .Y (n_259));
  AOI2BB1X1 g9444(.A0N (n_155), .A1N (n_221), .B0 (n_49), .Y (n_258));
  AOI21X2 g9445(.A0 (n_151), .A1 (n_222), .B0 (n_50), .Y (n_257));
  AOI21X2 g9446(.A0 (n_154), .A1 (n_226), .B0 (n_31), .Y (n_256));
  AOI21X1 g9447(.A0 (n_7), .A1 (n_160), .B0 (n_121), .Y (n_255));
  NOR2BX1 g9448(.AN (n_249), .B (n_776), .Y (n_254));
  XNOR2X1 g9449(.A (RdIndex[3]), .B (n_219), .Y (n_253));
  MXI2XL g9450(.A (counter[4]), .B (n_119), .S0 (n_230), .Y (n_252));
  MX2X1 g9452(.A (n_41), .B (n_114), .S0 (n_230), .Y (n_250));
  AOI21X2 g9453(.A0 (n_175), .A1 (n_177), .B0 (n_8), .Y (n_267));
  NOR2X2 g9455(.A (n_155), .B (n_227), .Y (n_247));
  NOR2BX1 g9457(.AN (mode), .B (n_212), .Y (n_245));
  AND2X1 g9458(.A (n_218), .B (n_63), .Y (n_244));
  NOR2BX1 g9459(.AN (n_220), .B (n_577), .Y (n_243));
  OR2X1 g9460(.A (n_28), .B (n_7), .Y (n_242));
  OR2X1 g9462(.A (WrIndex0[1]), .B (n_7), .Y (n_249));
  INVX3 g9463(.A (n_239), .Y (n_240));
  INVX1 g9464(.A (n_238), .Y (n_237));
  NOR2X1 g9465(.A (n_153), .B (n_227), .Y (n_236));
  NOR2X1 g9467(.A (n_67), .B (n_213), .Y (n_235));
  AOI22X1 g9468(.A0 (n_22), .A1 (n_597), .B0 (n_149), .B1 (n_208), .Y
       (n_234));
  NOR2X4 g9472(.A (n_94), .B (n_217), .Y (n_239));
  NAND2X4 g9473(.A (validIn), .B (n_229), .Y (n_238));
  INVX4 g9476(.A (n_228), .Y (n_227));
  INVX3 g9477(.A (n_225), .Y (n_226));
  INVX3 g9479(.A (n_221), .Y (n_222));
  ADDHX1 g9480(.A (n_662), .B (n_173), .CO (n_219), .S (n_220));
  ADDHX1 g9481(.A (counter[2]), .B (n_171), .CO (n_230), .S (n_218));
  AOI21X4 g9482(.A0 (n_181), .A1 (n_189), .B0 (n_64), .Y (n_217));
  NOR2BX4 g9484(.AN (n_561), .B (n_200), .Y (n_229));
  NOR2X4 g9485(.A (n_37), .B (n_785), .Y (n_228));
  OR2X6 g9486(.A (n_37), .B (n_598), .Y (n_225));
  NOR2X6 g9487(.A (WrIndex1[2]), .B (n_785), .Y (n_224));
  OR2X6 g9488(.A (WrIndex1[2]), .B (n_598), .Y (n_221));
  MXI2XL g9489(.A (current_buf), .B (n_567), .S0 (n_190), .Y (n_213));
  MXI2XL g9490(.A (n_193), .B (counter2[1]), .S0 (n_96), .Y (n_212));
  NOR2X2 g9494(.A (n_179), .B (n_207), .Y (n_215));
  NOR2BX2 g9497(.AN (WrIndex0[1]), .B (n_188), .Y (n_207));
  NOR2BX2 g9503(.AN (n_580), .B (n_24), .Y (n_208));
  OAI21X2 g9509(.A0 (n_580), .A1 (n_177), .B0 (n_175), .Y (n_202));
  NAND2BX2 g9511(.AN (n_195), .B (n_575), .Y (n_200));
  NOR2X4 g9512(.A (n_60), .B (n_183), .Y (n_199));
  AND2X1 g9513(.A (n_172), .B (n_63), .Y (n_196));
  OAI2BB1X1 g9514(.A0N (counter2[1]), .A1N (counter2[0]), .B0
       (counter[1]), .Y (n_195));
  NOR2BX1 g9515(.AN (mode), .B (n_167), .Y (n_194));
  AND2X1 g9516(.A (n_571), .B (n_142), .Y (n_193));
  NOR2BX1 g9519(.AN (n_174), .B (n_577), .Y (n_191));
  NOR2X1 g9520(.A (n_25), .B (n_161), .Y (n_190));
  AOI21X2 g9525(.A0 (n_93), .A1 (n_146), .B0 (n_162), .Y (n_183));
  AOI21X2 g9526(.A0 (n_136), .A1 (n_116), .B0 (n_103), .Y (n_182));
  AOI21X2 g9527(.A0 (n_61), .A1 (n_134), .B0 (n_4), .Y (n_189));
  NAND2X4 g9528(.A (n_169), .B (n_130), .Y (n_188));
  INVX1 g9530(.A (n_179), .Y (n_178));
  INVX2 g9531(.A (n_176), .Y (n_177));
  ADDHX1 g9532(.A (RdIndex[1]), .B (RdIndex[0]), .CO (n_173), .S
       (n_174));
  ADDHX1 g9533(.A (counter[1]), .B (n_0), .CO (n_171), .S (n_172));
  ADDHX1 g9534(.A (n_744), .B (counter[0]), .CO (n_169), .S (n_170));
  NOR2BX1 g9535(.AN (n_145), .B (n_571), .Y (n_168));
  NAND2X2 g9537(.A (n_744), .B (n_144), .Y (n_181));
  NOR2X4 g9539(.A (n_98), .B (n_143), .Y (n_179));
  OAI21X4 g9540(.A0 (n_75), .A1 (n_126), .B0 (n_499), .Y (n_176));
  OR2X2 g9541(.A (n_567), .B (n_143), .Y (n_175));
  MXI2XL g9542(.A (n_71), .B (counter2[0]), .S0 (n_96), .Y (n_167));
  NAND2X1 g9545(.A (n_140), .B (n_132), .Y (n_164));
  NOR4X2 g9547(.A (counter[1]), .B (n_706), .C (n_98), .D (n_570), .Y
       (n_162));
  NOR4X1 g9548(.A (n_576), .B (n_599), .C (n_581), .D (n_64), .Y
       (n_161));
  INVX1 g9550(.A (n_153), .Y (n_152));
  NAND2X1 g9551(.A (n_127), .B (n_122), .Y (n_150));
  NOR2X1 g9552(.A (WrIndex1[3]), .B (n_123), .Y (n_149));
  NOR2BX1 g9553(.AN (n_95), .B (n_571), .Y (n_148));
  NAND2BX2 g9554(.AN (n_92), .B (n_2), .Y (n_160));
  NOR2X2 g9555(.A (WrIndex1[3]), .B (n_122), .Y (n_159));
  NOR2X2 g9556(.A (WrIndex1[3]), .B (n_133), .Y (n_158));
  NOR2X2 g9557(.A (n_27), .B (n_127), .Y (n_157));
  NOR2X2 g9558(.A (WrIndex1[3]), .B (n_124), .Y (n_156));
  OR2X1 g9559(.A (n_39), .B (n_131), .Y (n_155));
  NOR2X2 g9560(.A (n_27), .B (n_124), .Y (n_154));
  NAND2X2 g9561(.A (WrIndex1[3]), .B (n_123), .Y (n_153));
  NOR2X2 g9563(.A (WrIndex1[3]), .B (n_127), .Y (n_151));
  XOR2X1 g9566(.A (counter2[0]), .B (counter2[1]), .Y (n_142));
  NOR3X2 g9568(.A (n_65), .B (n_0), .C (n_436), .Y (n_140));
  AOI2BB1X1 g9569(.A0N (n_38), .A1N (WrIndex1[2]), .B0 (n_27), .Y
       (n_139));
  NOR2X1 g9572(.A (n_60), .B (n_99), .Y (n_137));
  NAND2X2 g9573(.A (n_94), .B (n_125), .Y (n_136));
  NAND3BX1 g9574(.AN (n_567), .B (in[1]), .C (n_562), .Y (n_135));
  OAI21X1 g9575(.A0 (n_26), .A1 (n_569), .B0 (n_62), .Y (n_134));
  NOR2X4 g9576(.A (n_0), .B (n_126), .Y (n_146));
  AND2X1 g9577(.A (n_92), .B (n_95), .Y (n_145));
  NAND2BX2 g9578(.AN (n_436), .B (n_100), .Y (n_144));
  NAND2X6 g9579(.A (n_26), .B (n_130), .Y (n_143));
  INVX1 g9580(.A (n_129), .Y (n_128));
  INVX4 g9581(.A (n_125), .Y (n_126));
  INVX1 g9582(.A (n_123), .Y (n_122));
  BUFX2 g9586(.A (n_121), .Y (n_52));
  NOR2X1 g9588(.A (n_41), .B (n_706), .Y (n_119));
  AND2X1 g9591(.A (n_436), .B (n_26), .Y (n_116));
  NAND2X1 g9593(.A (n_41), .B (n_62), .Y (n_114));
  NAND2X1 g9596(.A (n_25), .B (buffer1[2]), .Y (n_111));
  NAND2X1 g9600(.A (n_55), .B (buffer1[11]), .Y (n_107));
  NOR2X1 g9601(.A (counter[0]), .B (n_673), .Y (n_106));
  NAND2X1 g9602(.A (n_25), .B (buffer1[10]), .Y (n_105));
  NOR2X1 g9603(.A (n_9), .B (WrIndex1[2]), .Y (n_104));
  NOR2X1 g9604(.A (n_26), .B (n_562), .Y (n_103));
  OR2X1 g9606(.A (n_38), .B (n_39), .Y (n_133));
  NOR2X2 g9607(.A (n_567), .B (n_570), .Y (n_132));
  OR2X1 g9608(.A (WrIndex1[1]), .B (n_27), .Y (n_131));
  NOR2X6 g9609(.A (n_706), .B (n_432), .Y (n_130));
  NOR2X1 g9610(.A (WrIndex0[0]), .B (n_28), .Y (n_129));
  NAND2X2 g9611(.A (n_38), .B (WrIndex1[0]), .Y (n_127));
  NOR2X4 g9612(.A (n_706), .B (n_68), .Y (n_125));
  NAND2X2 g9613(.A (n_38), .B (n_39), .Y (n_124));
  NOR2X2 g9614(.A (WrIndex1[1]), .B (WrIndex1[0]), .Y (n_123));
  NAND2X1 g9615(.A (WrIndex0[3]), .B (WrIndex0[2]), .Y (n_121));
  INVX2 g9616(.A (n_100), .Y (n_101));
  INVX1 g9617(.A (n_2), .Y (n_97));
  INVX2 g9618(.A (n_94), .Y (n_93));
  BUFX2 g9622(.A (n_51), .Y (n_89));
  INVX1 g9623(.A (n_88), .Y (n_87));
  NAND2X1 g9624(.A (in[1]), .B (n_0), .Y (n_86));
  NAND2X1 g9626(.A (n_25), .B (buffer1[6]), .Y (n_84));
  NOR2X1 g9631(.A (RdIndex[0]), .B (n_684), .Y (n_79));
  NAND2X1 g9633(.A (n_55), .B (buffer1[0]), .Y (n_77));
  NAND2BX1 g9635(.AN (n_567), .B (n_0), .Y (n_75));
  NAND2X1 g9636(.A (n_25), .B (buffer1[8]), .Y (n_74));
  NAND2X1 g9638(.A (validIn), .B (n_38), .Y (n_73));
  NOR2BX1 g9640(.AN (n_571), .B (counter2[0]), .Y (n_71));
  NAND2X1 g9642(.A (n_55), .B (buffer1[15]), .Y (n_69));
  NOR2X4 g9643(.A (n_26), .B (n_570), .Y (n_100));
  NAND2X1 g9644(.A (WrIndex0[0]), .B (n_28), .Y (n_99));
  OR2X1 g9645(.A (mode), .B (current_buf), .Y (n_98));
  NOR2X1 g9647(.A (n_578), .B (n_571), .Y (n_96));
  NAND2X2 g9648(.A (WrIndex0[0]), .B (WrIndex0[1]), .Y (n_95));
  AND2X4 g9649(.A (n_61), .B (current_buf), .Y (n_94));
  OR2X1 g9650(.A (WrIndex0[1]), .B (WrIndex0[0]), .Y (n_92));
  OR2X2 g9651(.A (WrIndex0[2]), .B (n_29), .Y (n_91));
  OR2X2 g9652(.A (WrIndex0[3]), .B (WrIndex0[2]), .Y (n_51));
  OR2X2 g9653(.A (WrIndex0[3]), .B (n_40), .Y (n_88));
  BUFX2 g9672(.A (WrIndex1[1]), .Y (n_38));
  BUFX2 g9674(.A (reset), .Y (n_67));
  INVX1 g9676(.A (in[2]), .Y (n_65));
  INVX1 g9678(.A (n_572), .Y (n_64));
  INVX1 g9688(.A (n_578), .Y (n_63));
  INVX2 g9690(.A (n_744), .Y (n_61));
  INVX1 g9693(.A (validIn), .Y (n_60));
  BUFX2 g9698(.A (n_24), .Y (n_25));
  INVX1 g9700(.A (n_22), .Y (n_58));
  INVX1 g9702(.A (n_22), .Y (n_23));
  INVX1 g9711(.A (n_20), .Y (n_57));
  INVX1 g9712(.A (n_20), .Y (n_21));
  BUFX2 g9714(.A (n_55), .Y (n_56));
  INVX1 g9716(.A (n_19), .Y (n_54));
  BUFX2 g9717(.A (n_55), .Y (n_19));
  BUFX2 g9718(.A (n_20), .Y (n_55));
  BUFX2 g9719(.A (n_24), .Y (n_20));
  INVX1 g9722(.A (n_25), .Y (n_53));
  INVX1 g9726(.A (n_24), .Y (n_22));
  INVX2 g9727(.A (validIn), .Y (n_24));
  DFFX1 \WrIndex0_reg[1] (.CK (rc_gclk_6717), .D (n_405), .Q
       (WrIndex0[1]), .QN (n_28));
  DFFX1 \WrIndex0_reg[2] (.CK (rc_gclk_6717), .D (n_430), .Q
       (WrIndex0[2]), .QN (n_40));
  DFFX1 \WrIndex0_reg[3] (.CK (rc_gclk_6717), .D (n_431), .Q
       (WrIndex0[3]), .QN (n_29));
  DFFX1 \WrIndex1_reg[0] (.CK (rc_gclk_6720), .D (n_395), .Q
       (WrIndex1[0]), .QN (n_39));
  DFFX1 \WrIndex1_reg[2] (.CK (rc_gclk_6720), .D (n_426), .Q
       (WrIndex1[2]), .QN (n_37));
  DFFX1 \WrIndex1_reg[3] (.CK (rc_gclk_6720), .D (n_429), .Q
       (WrIndex1[3]), .QN (n_27));
  DFFX4 \counter_reg[0] (.CK (clk), .D (n_106), .Q (counter[0]), .QN
       (n_26));
  DFFX4 \counter_reg[3] (.CK (rc_gclk_6725), .D (n_307), .Q
       (counter[3]), .QN (n_41));
  INVX1 drc_bufs9731(.A (reset), .Y (n_18));
  INVX1 drc_bufs9732(.A (reset), .Y (n_17));
  INVX1 drc_bufs9733(.A (reset), .Y (n_16));
  INVX1 drc_bufs9734(.A (reset), .Y (n_15));
  INVX1 drc_bufs9740(.A (n_20), .Y (n_13));
  BUFX2 drc_bufs9749(.A (n_91), .Y (n_12));
  BUFX2 drc_bufs9754(.A (n_67), .Y (n_11));
  BUFX2 drc_bufs9759(.A (n_88), .Y (n_10));
  BUFX2 drc_bufs9764(.A (WrIndex1[3]), .Y (n_9));
  NAND2BX4 g6663(.AN (n_229), .B (validIn), .Y (n_8));
  NAND2BX4 g9790(.AN (n_200), .B (n_1), .Y (n_7));
  NOR2BX1 g9792(.AN (n_154), .B (n_227), .Y (n_5));
  NOR2BX1 g9793(.AN (n_432), .B (n_0), .Y (n_4));
  NOR2BX2 g9795(.AN (n_571), .B (n_24), .Y (n_2));
  NOR2BX1 g9796(.AN (validIn), .B (n_101), .Y (n_1));
  OAI21X1 g9804(.A0 (n_145), .A1 (n_97), .B0 (n_254), .Y (n_592));
  NOR2BX2 g9805(.AN (n_200), .B (n_188), .Y (n_593));
  OAI2BB1X1 g3(.A0N (current_buf), .A1N (n_181), .B0 (in[0]), .Y
       (n_594));
  MXI2X1 g9807(.A (n_596), .B (n_153), .S0 (n_580), .Y (n_597));
  NAND2BX4 g9808(.AN (n_131), .B (n_176), .Y (n_596));
  NAND2X2 g9809(.A (n_132), .B (n_182), .Y (n_598));
  INVX2 drc_bufs(.A (n_601), .Y (n_599));
  INVX1 drc_bufs9811(.A (n_582), .Y (n_601));
  BUFX3 drc_buf_sp9821(.A (counter[0]), .Y (n_0));
  BUFX2 drc_buf_sp9868(.A (RdIndex[2]), .Y (n_662));
  BUFX2 drc_buf_sp9878(.A (n_578), .Y (n_673));
  BUFX2 drc_buf_sp9888(.A (n_577), .Y (n_684));
  BUFX2 fopt9909(.A (counter[4]), .Y (n_706));
  BUFX3 fopt9945(.A (mode), .Y (n_744));
  NOR2BX2 g9947(.AN (n_224), .B (n_155), .Y (n_751));
  NOR2BX1 g9948(.AN (n_92), .B (n_97), .Y (n_752));
  OAI2BB1X1 g9949(.A0N (n_23), .A1N (buffer0[10]), .B0 (n_386), .Y
       (n_753));
  OAI2BB1X1 g9950(.A0N (n_23), .A1N (buffer0[3]), .B0 (n_401), .Y
       (n_754));
  OAI2BB1X1 g9951(.A0N (n_58), .A1N (buffer0[11]), .B0 (n_397), .Y
       (n_755));
  OAI2BB1X1 g9952(.A0N (n_58), .A1N (buffer0[7]), .B0 (n_396), .Y
       (n_756));
  OAI2BB1X1 g9953(.A0N (n_23), .A1N (buffer0[1]), .B0 (n_384), .Y
       (n_757));
  OAI2BB1X1 g9954(.A0N (n_23), .A1N (buffer0[2]), .B0 (n_389), .Y
       (n_758));
  OAI2BB1X1 g9955(.A0N (n_20), .A1N (buffer0[9]), .B0 (n_388), .Y
       (n_759));
  OAI2BB1X1 g9956(.A0N (n_23), .A1N (buffer0[0]), .B0 (n_387), .Y
       (n_760));
  OAI2BB1X1 g9957(.A0N (n_58), .A1N (buffer0[12]), .B0 (n_404), .Y
       (n_761));
  OAI2BB1X1 g9958(.A0N (n_23), .A1N (buffer0[13]), .B0 (n_403), .Y
       (n_762));
  OAI2BB1X1 g9959(.A0N (n_23), .A1N (buffer0[14]), .B0 (n_402), .Y
       (n_763));
  OAI2BB1X1 g9960(.A0N (n_58), .A1N (buffer0[15]), .B0 (n_385), .Y
       (n_764));
  OAI2BB1X1 g9961(.A0N (n_20), .A1N (buffer0[4]), .B0 (n_398), .Y
       (n_765));
  OAI2BB1X1 g9962(.A0N (n_58), .A1N (buffer0[5]), .B0 (n_390), .Y
       (n_766));
  OAI2BB1X1 g9963(.A0N (n_58), .A1N (buffer0[6]), .B0 (n_383), .Y
       (n_767));
  OAI2BB1X1 g9964(.A0N (n_23), .A1N (buffer0[8]), .B0 (n_399), .Y
       (n_768));
  AOI33X2 g9965(.A0 (n_53), .A1 (n_154), .A2 (n_202), .B0 (n_285), .B1
       (n_9), .B2 (n_37), .Y (n_769));
  AOI2BB1X2 g9966(.A0N (n_25), .A1N (n_772), .B0 (n_775), .Y (n_770));
  AOI21X2 g9967(.A0 (n_139), .A1 (n_237), .B0 (n_315), .Y (n_771));
  OA22X1 g9968(.A0 (WrIndex0[0]), .A1 (n_215), .B0 (WrIndex0[1]), .B1
       (n_282), .Y (n_772));
  OAI2BB1X1 g9971(.A0N (n_148), .A1N (n_199), .B0 (n_242), .Y (n_775));
  NOR4BBX2 g9972(.AN (n_137), .BN (n_130), .C (n_94), .D (n_170), .Y
       (n_776));
  OAI211X2 g9973(.A0 (n_65), .A1 (n_178), .B0 (n_781), .C0 (n_780), .Y
       (n_777));
  OAI21X2 g9975(.A0 (n_135), .A1 (n_101), .B0 (n_164), .Y (n_779));
  NAND3BX2 g9976(.AN (n_144), .B (in[3]), .C (n_744), .Y (n_780));
  OR3X1 g9977(.A (n_86), .B (n_98), .C (n_126), .Y (n_781));
  OAI21X1 g9978(.A0 (n_782), .A1 (n_91), .B0 (n_309), .Y (n_783));
  AOI2BB1X1 g9979(.A0N (n_25), .A1N (n_215), .B0 (n_199), .Y (n_782));
  AOI21X4 g9980(.A0 (n_784), .A1 (n_146), .B0 (n_779), .Y (n_785));
  NOR2BX2 g9981(.AN (in[0]), .B (n_93), .Y (n_784));
  AOI2BB1X4 g9982(.A0N (n_594), .A1N (n_572), .B0 (n_777), .Y (n_786));
endmodule

