
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
// Generated on: May  6 2016 19:12:01

// Verification Directory fv/rsc 

module rsc(clk, in, x_out, z_out, rst_N, mode, mode_out, valid_out);
  input clk, in, rst_N, mode;
  output x_out, z_out, mode_out, valid_out;
  wire clk, in, rst_N, mode;
  wire x_out, z_out, mode_out, valid_out;
  wire IN, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, d1,
       d2, d3;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_24;
  XNOR2X1 g120(.A (n_24), .B (d1), .Y (n_9));
  XNOR2X1 g121(.A (n_7), .B (n_8), .Y (n_24));
  MXI2X1 g122(.A (IN), .B (n_7), .S0 (mode), .Y (n_8));
  XNOR2X1 g123(.A (d2), .B (d3), .Y (n_7));
  DFFHQX1 d3_reg(.CK (clk), .D (n_6), .Q (d3));
  AND2X1 g126(.A (d2), .B (rst_N), .Y (n_6));
  DFFTRXL IN_reg(.CK (clk), .D (rst_N), .RN (in), .Q (UNCONNECTED), .QN
       (IN));
  DFFHQX1 d2_reg(.CK (clk), .D (n_3), .Q (d2));
  DFFRX1 valid_out_reg(.RN (1'b1), .CK (clk), .D (rst_N), .Q
       (UNCONNECTED0), .QN (n_5));
  INVX12 g130(.A (n_5), .Y (valid_out));
  DFFRX1 mode_out_reg(.RN (1'b1), .CK (clk), .D (mode), .Q
       (UNCONNECTED1), .QN (n_4));
  INVX12 g132(.A (n_4), .Y (mode_out));
  AND2X1 g133(.A (d1), .B (rst_N), .Y (n_3));
  INVX12 drc_bufs134(.A (n_1), .Y (x_out));
  INVX1 drc_bufs135(.A (n_8), .Y (n_1));
  BUFX12 drc_bufs137(.A (n_0), .Y (z_out));
  XNOR2X1 g2(.A (d3), .B (n_9), .Y (n_0));
  DFFTRXL d1_reg(.CK (clk), .D (n_24), .RN (rst_N), .Q (d1), .QN
       (UNCONNECTED2));
endmodule

