
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
// Generated on: Apr 27 2016 23:02:34

// Verification Directory fv/output_block 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_1(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module RC_CG_MOD_2(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module output_block(in, clk, reset, mode, validIn, out0, out1,
     validOut);
  input [3:0] in;
  input clk, reset, mode, validIn;
  output out0, out1, validOut;
  wire [3:0] in;
  wire clk, reset, mode, validIn;
  wire out0, out1, validOut;
  wire [3:0] RdIndex;
  wire [4:0] counter;
  wire [15:0] buffer;
  wire [3:0] WrIndex;
  wire RdStart, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_74, n_75, n_76, n_77, n_78, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_185, n_221, n_222;
  wire n_225, n_228, n_229, rc_gclk, rc_gclk_2093, rc_gclk_2095;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_222), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  RC_CG_MOD_1 RC_CG_HIER_INST1(.enable (n_221), .ck_in (clk), .ck_out
       (rc_gclk_2093), .test (1'b0));
  RC_CG_MOD_2 RC_CG_HIER_INST2(.enable (n_185), .ck_in (clk), .ck_out
       (rc_gclk_2095), .test (1'b0));
  TBUFX12 out0_tri(.A (n_175), .OE (n_176), .Y (out0));
  TBUFX12 out1_tri(.A (n_174), .OE (n_176), .Y (out1));
  SMDFFHQX1 out0_reg(.CK (rc_gclk_2095), .D0 (n_169), .D1 (n_168), .S0
       (RdIndex[1]), .SE (RdIndex[0]), .SI (n_172), .Q (n_175));
  SDFFQX1 out1_reg(.CK (rc_gclk_2095), .D (n_172), .SI (n_171), .SE
       (RdIndex[0]), .Q (n_174));
  DFFTRX1 validOut_reg(.CK (rc_gclk_2095), .D (n_185), .RN (n_159), .Q
       (UNCONNECTED), .QN (n_173));
  INVX12 g2368(.A (n_173), .Y (validOut));
  MX2X1 g2369(.A (n_168), .B (n_166), .S0 (RdIndex[1]), .Y (n_171));
  MX2X1 g2370(.A (n_167), .B (n_165), .S0 (RdIndex[1]), .Y (n_172));
  OR2X1 g2371(.A (n_2), .B (n_170), .Y (n_222));
  NOR3X1 g2372(.A (counter[0]), .B (counter[4]), .C (n_164), .Y
       (n_170));
  MX3XL g2373(.A (buffer[0]), .B (buffer[8]), .C (n_162), .S0
       (RdIndex[3]), .S1 (RdIndex[2]), .Y (n_169));
  OAI21X1 g2374(.A0 (counter[0]), .A1 (n_163), .B0 (n_159), .Y (n_185));
  MX4XL g2375(.A (buffer[1]), .B (buffer[9]), .C (buffer[5]), .D
       (buffer[13]), .S0 (RdIndex[3]), .S1 (RdIndex[2]), .Y (n_167));
  MX2X1 g2376(.A (n_162), .B (buffer[8]), .S0 (RdIndex[2]), .Y (n_166));
  MX4XL g2377(.A (buffer[3]), .B (buffer[11]), .C (buffer[7]), .D
       (buffer[15]), .S0 (RdIndex[3]), .S1 (RdIndex[2]), .Y (n_165));
  MX4XL g2378(.A (buffer[2]), .B (buffer[10]), .C (buffer[6]), .D
       (buffer[14]), .S0 (RdIndex[3]), .S1 (RdIndex[2]), .Y (n_168));
  NAND2X1 g2379(.A (n_159), .B (n_163), .Y (n_221));
  MXI2XL g2380(.A (n_160), .B (n_161), .S0 (counter[3]), .Y (n_164));
  DFFRX1 out0_reg403(.RN (1'b1), .CK (clk), .D (n_225), .Q
       (UNCONNECTED0), .QN (n_176));
  OAI2BB1X1 g2382(.A0N (counter[3]), .A1N (counter[4]), .B0 (n_160), .Y
       (n_163));
  MX2X1 g2383(.A (buffer[4]), .B (buffer[12]), .S0 (RdIndex[3]), .Y
       (n_162));
  NOR2BX1 g2384(.AN (counter[2]), .B (counter[1]), .Y (n_161));
  INVX1 g2386(.A (n_225), .Y (n_159));
  NOR2X1 g2387(.A (counter[2]), .B (counter[1]), .Y (n_160));
  NAND2BX2 g2388(.AN (reset), .B (RdStart), .Y (n_225));
  NAND2BX4 g2(.AN (reset), .B (validIn), .Y (n_2));
  DFFTRXL \buffer_reg[15] (.CK (rc_gclk), .D (n_157), .RN (n_14), .Q
       (buffer[15]), .QN (UNCONNECTED1));
  DFFTRXL \buffer_reg[7] (.CK (rc_gclk), .D (n_158), .RN (n_9), .Q
       (buffer[7]), .QN (UNCONNECTED2));
  DFFTRXL \buffer_reg[11] (.CK (rc_gclk), .D (n_154), .RN (n_9), .Q
       (buffer[11]), .QN (UNCONNECTED3));
  SDFFQX1 RdStart_reg(.CK (clk), .D (RdStart), .SI (n_18), .SE (n_142),
       .Q (RdStart));
  OAI221X1 g4169(.A0 (n_78), .A1 (n_25), .B0 (n_58), .B1 (n_12), .C0
       (n_155), .Y (n_158));
  OAI221X1 g4170(.A0 (n_78), .A1 (n_36), .B0 (n_58), .B1 (n_27), .C0
       (n_156), .Y (n_157));
  DFFHQX1 \buffer_reg[10] (.CK (rc_gclk), .D (n_152), .Q (buffer[10]));
  DFFHQX1 \buffer_reg[14] (.CK (rc_gclk), .D (n_153), .Q (buffer[14]));
  DFFHQX1 \buffer_reg[6] (.CK (rc_gclk), .D (n_151), .Q (buffer[6]));
  DFFHQX1 \RdIndex_reg[3] (.CK (rc_gclk_2093), .D (n_148), .Q
       (RdIndex[3]));
  OAI2BB1X1 g4175(.A0N (n_7), .A1N (n_141), .B0 (buffer[15]), .Y
       (n_156));
  OAI2BB1X1 g4176(.A0N (n_6), .A1N (n_141), .B0 (buffer[7]), .Y
       (n_155));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_150), .Q (counter[3]));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_149), .Q (counter[4]));
  DFFHQX1 \buffer_reg[2] (.CK (rc_gclk), .D (n_146), .Q (buffer[2]));
  DFFHQX1 \buffer_reg[12] (.CK (rc_gclk), .D (n_143), .Q (buffer[12]));
  DFFQXL \buffer_reg[8] (.CK (rc_gclk), .D (n_136), .Q (buffer[8]));
  DFFHQX1 \buffer_reg[4] (.CK (rc_gclk), .D (n_147), .Q (buffer[4]));
  DFFTRXL \buffer_reg[9] (.CK (rc_gclk), .D (n_121), .RN (n_9), .Q
       (buffer[9]), .QN (UNCONNECTED4));
  DFFTRXL \buffer_reg[3] (.CK (rc_gclk), .D (n_126), .RN (n_14), .Q
       (buffer[3]), .QN (UNCONNECTED5));
  DFFTRXL \buffer_reg[5] (.CK (rc_gclk), .D (n_123), .RN (n_9), .Q
       (buffer[5]), .QN (UNCONNECTED6));
  DFFQX2 \WrIndex_reg[2] (.CK (rc_gclk), .D (n_145), .Q (WrIndex[2]));
  OAI2BB1X1 g4187(.A0N (buffer[11]), .A1N (n_118), .B0 (n_107), .Y
       (n_154));
  NOR2X1 g4188(.A (n_3), .B (n_137), .Y (n_153));
  NOR2X1 g4189(.A (n_3), .B (n_228), .Y (n_152));
  NOR2X1 g4190(.A (n_2), .B (n_138), .Y (n_151));
  NOR2X1 g4191(.A (reset), .B (n_134), .Y (n_150));
  NOR2X1 g4192(.A (reset), .B (n_135), .Y (n_149));
  NOR2X1 g4193(.A (n_225), .B (n_139), .Y (n_148));
  DFFTRXL \buffer_reg[13] (.CK (rc_gclk), .D (n_124), .RN (n_9), .Q
       (buffer[13]), .QN (UNCONNECTED7));
  DFFHQX1 \WrIndex_reg[3] (.CK (rc_gclk), .D (n_144), .Q (WrIndex[3]));
  NOR2X1 g4196(.A (n_2), .B (n_125), .Y (n_147));
  NOR2X1 g4197(.A (n_2), .B (n_131), .Y (n_146));
  NOR2X1 g4198(.A (n_3), .B (n_133), .Y (n_145));
  AND2X1 g4199(.A (n_122), .B (n_9), .Y (n_144));
  NOR2X1 g4200(.A (n_2), .B (n_127), .Y (n_143));
  NAND2X1 g4201(.A (n_18), .B (n_128), .Y (n_142));
  DFFHQX1 \RdIndex_reg[2] (.CK (rc_gclk_2093), .D (n_129), .Q
       (RdIndex[2]));
  DFFQXL \counter_reg[2] (.CK (clk), .D (n_130), .Q (counter[2]));
  XNOR2X1 g4205(.A (RdIndex[3]), .B (n_114), .Y (n_139));
  AOI221X1 g4206(.A0 (n_0), .A1 (n_10), .B0 (buffer[6]), .B1 (n_89),
       .C0 (n_109), .Y (n_138));
  AOI21X1 g4207(.A0 (buffer[14]), .A1 (n_88), .B0 (n_229), .Y (n_137));
  AOI21X1 g4208(.A0 (n_98), .A1 (n_105), .B0 (n_2), .Y (n_136));
  MXI2XL g4209(.A (counter[4]), .B (n_21), .S0 (n_117), .Y (n_135));
  MXI2XL g4210(.A (counter[3]), .B (n_24), .S0 (n_117), .Y (n_134));
  AOI21X1 g4211(.A0 (n_17), .A1 (n_103), .B0 (n_132), .Y (n_141));
  ADDHX1 g4212(.A (n_87), .B (WrIndex[2]), .CO (n_132), .S (n_133));
  AOI22X1 g4213(.A0 (n_97), .A1 (n_10), .B0 (buffer[2]), .B1 (n_84), .Y
       (n_131));
  AND2X1 g4214(.A (n_116), .B (n_18), .Y (n_130));
  NOR2BX1 g4215(.AN (n_115), .B (n_225), .Y (n_129));
  NAND2BX1 g4216(.AN (n_44), .B (n_117), .Y (n_128));
  AOI21X1 g4217(.A0 (buffer[12]), .A1 (n_101), .B0 (n_106), .Y (n_127));
  OAI21X1 g4218(.A0 (n_78), .A1 (n_12), .B0 (n_108), .Y (n_126));
  DFFHQX1 \buffer_reg[1] (.CK (rc_gclk), .D (n_110), .Q (buffer[1]));
  AOI222X1 g4220(.A0 (n_86), .A1 (n_11), .B0 (n_53), .B1 (n_26), .C0
       (buffer[4]), .C1 (n_77), .Y (n_125));
  OAI211X1 g4221(.A0 (n_59), .A1 (n_27), .B0 (n_90), .C0 (n_112), .Y
       (n_124));
  OAI221X1 g4222(.A0 (n_59), .A1 (n_12), .B0 (n_69), .B1 (n_25), .C0
       (n_113), .Y (n_123));
  OAI211X1 g4223(.A0 (n_87), .A1 (n_25), .B0 (n_102), .C0 (n_27), .Y
       (n_122));
  OAI211X1 g4224(.A0 (n_59), .A1 (n_25), .B0 (n_94), .C0 (n_111), .Y
       (n_121));
  OAI211X1 g4227(.A0 (n_104), .A1 (n_25), .B0 (n_102), .C0 (n_47), .Y
       (n_118));
  ADDHX1 g4228(.A (counter[2]), .B (n_65), .CO (n_117), .S (n_116));
  ADDHX1 g4229(.A (RdIndex[2]), .B (n_67), .CO (n_114), .S (n_115));
  NAND2BX1 g4230(.AN (n_92), .B (buffer[5]), .Y (n_113));
  NAND2X1 g4231(.A (buffer[13]), .B (n_93), .Y (n_112));
  NAND2X1 g4232(.A (buffer[9]), .B (n_96), .Y (n_111));
  DFFHQX1 \buffer_reg[0] (.CK (rc_gclk), .D (n_100), .Q (buffer[0]));
  DFFQX2 \WrIndex_reg[1] (.CK (rc_gclk), .D (n_99), .Q (WrIndex[1]));
  AOI21X1 g4235(.A0 (n_80), .A1 (n_61), .B0 (n_3), .Y (n_110));
  AND2X1 g4236(.A (n_26), .B (n_97), .Y (n_109));
  OAI21X1 g4237(.A0 (n_87), .A1 (n_12), .B0 (buffer[3]), .Y (n_108));
  OA22X1 g4238(.A0 (n_78), .A1 (n_27), .B0 (n_58), .B1 (n_25), .Y
       (n_107));
  OAI2BB1X1 g4239(.A0N (n_86), .A1N (n_28), .B0 (n_91), .Y (n_106));
  AOI222X1 g4240(.A0 (n_86), .A1 (n_26), .B0 (n_70), .B1 (n_11), .C0
       (n_53), .C1 (n_28), .Y (n_105));
  INVX1 g4241(.A (n_103), .Y (n_104));
  OAI2BB1X1 g4242(.A0N (n_54), .A1N (n_17), .B0 (n_74), .Y (n_101));
  NOR2X1 g4243(.A (n_3), .B (n_76), .Y (n_100));
  NOR2X1 g4244(.A (n_3), .B (n_85), .Y (n_99));
  NAND2BX1 g4245(.AN (n_75), .B (buffer[8]), .Y (n_98));
  OAI21X1 g4246(.A0 (n_63), .A1 (WrIndex[1]), .B0 (n_54), .Y (n_103));
  NAND2X1 g4247(.A (n_87), .B (n_7), .Y (n_102));
  DFFHQX1 \RdIndex_reg[1] (.CK (rc_gclk_2093), .D (n_81), .Q
       (RdIndex[1]));
  DFFQXL \counter_reg[1] (.CK (clk), .D (n_83), .Q (counter[1]));
  DFFQX2 \WrIndex_reg[0] (.CK (rc_gclk), .D (n_82), .Q (WrIndex[0]));
  OAI2BB1X1 g4251(.A0N (n_1), .A1N (n_57), .B0 (n_71), .Y (n_96));
  OAI221X2 g4252(.A0 (n_6), .A1 (n_56), .B0 (n_29), .B1 (n_7), .C0
       (n_47), .Y (n_95));
  OA22X1 g4253(.A0 (n_69), .A1 (n_27), .B0 (n_50), .B1 (n_52), .Y
       (n_94));
  OAI2BB1X1 g4254(.A0N (n_17), .A1N (n_57), .B0 (n_72), .Y (n_93));
  AOI221X1 g4255(.A0 (WrIndex[2]), .A1 (n_4), .B0 (n_57), .B1 (n_10),
       .C0 (n_7), .Y (n_92));
  AOI22X1 g4256(.A0 (n_70), .A1 (n_26), .B0 (n_53), .B1 (n_37), .Y
       (n_91));
  OA22X1 g4257(.A0 (n_69), .A1 (n_36), .B0 (n_51), .B1 (n_52), .Y
       (n_90));
  OAI211X1 g4258(.A0 (n_56), .A1 (n_25), .B0 (n_55), .C0 (n_6), .Y
       (n_89));
  OAI211X1 g4259(.A0 (n_17), .A1 (n_56), .B0 (n_55), .C0 (n_7), .Y
       (n_88));
  MX2X1 g4260(.A (n_60), .B (n_33), .S0 (n_4), .Y (n_97));
  ADDHX1 g4261(.A (n_40), .B (n_5), .CO (n_87), .S (n_85));
  NAND2X1 g4262(.A (n_56), .B (n_10), .Y (n_84));
  AND2X1 g4263(.A (n_66), .B (n_18), .Y (n_83));
  NOR2X1 g4264(.A (n_2), .B (n_64), .Y (n_82));
  NOR2BX1 g4265(.AN (n_68), .B (n_225), .Y (n_81));
  OR2X1 g4266(.A (n_69), .B (n_12), .Y (n_80));
  AND2X1 g4268(.A (n_4), .B (n_60), .Y (n_86));
  OAI2BB1X1 g4269(.A0N (n_54), .A1N (n_11), .B0 (n_62), .Y (n_77));
  AOI22X1 g4270(.A0 (n_53), .A1 (n_11), .B0 (buffer[0]), .B1 (n_42), .Y
       (n_76));
  AOI222X1 g4271(.A0 (n_54), .A1 (WrIndex[2]), .B0 (n_31), .B1 (n_10),
       .C0 (n_7), .C1 (n_38), .Y (n_75));
  AOI221X1 g4272(.A0 (n_31), .A1 (n_8), .B0 (n_37), .B1 (n_38), .C0
       (n_10), .Y (n_74));
  AOI22X1 g4274(.A0 (n_52), .A1 (n_8), .B0 (n_4), .B1 (n_37), .Y
       (n_72));
  AOI221X1 g4275(.A0 (WrIndex[3]), .A1 (WrIndex[1]), .B0 (n_52), .B1
       (n_35), .C0 (n_37), .Y (n_71));
  OA22X1 g4276(.A0 (n_49), .A1 (n_5), .B0 (n_23), .B1 (n_40), .Y
       (n_78));
  ADDHX1 g4277(.A (RdIndex[1]), .B (RdIndex[0]), .CO (n_67), .S (n_68));
  ADDHX1 g4278(.A (counter[1]), .B (counter[0]), .CO (n_65), .S (n_66));
  ADDHX1 g4279(.A (mode), .B (WrIndex[0]), .CO (n_63), .S (n_64));
  AOI21X1 g4280(.A0 (WrIndex[2]), .A1 (n_38), .B0 (n_7), .Y (n_62));
  OAI2BB1X1 g4281(.A0N (n_5), .A1N (n_11), .B0 (buffer[1]), .Y (n_61));
  NOR2X1 g4282(.A (n_31), .B (n_48), .Y (n_70));
  OR2X1 g4284(.A (n_49), .B (n_4), .Y (n_69));
  MX2X1 g4285(.A (n_20), .B (in[1]), .S0 (WrIndex[0]), .Y (n_60));
  OA21X1 g4286(.A0 (n_32), .A1 (n_40), .B0 (n_45), .Y (n_59));
  AND2X1 g4287(.A (n_46), .B (n_43), .Y (n_58));
  MX2X1 g4288(.A (n_41), .B (n_40), .S0 (WrIndex[1]), .Y (n_57));
  MX2X1 g4289(.A (n_30), .B (n_5), .S0 (WrIndex[0]), .Y (n_56));
  NAND2X1 g4290(.A (in[2]), .B (n_26), .Y (n_51));
  NAND2X1 g4291(.A (in[2]), .B (n_11), .Y (n_50));
  NAND2X1 g4292(.A (n_30), .B (n_17), .Y (n_55));
  NAND2X2 g4293(.A (n_41), .B (WrIndex[1]), .Y (n_54));
  AND2X1 g4294(.A (n_39), .B (in[0]), .Y (n_53));
  OR2X1 g4295(.A (n_31), .B (n_16), .Y (n_52));
  DFFQXL \counter_reg[0] (.CK (clk), .D (n_22), .Q (counter[0]));
  DFFHQX1 \RdIndex_reg[0] (.CK (rc_gclk_2093), .D (n_34), .Q
       (RdIndex[0]));
  NAND3X1 g4299(.A (in[2]), .B (n_29), .C (WrIndex[0]), .Y (n_46));
  NAND3X1 g4300(.A (in[3]), .B (n_29), .C (n_16), .Y (n_45));
  NAND3BX1 g4301(.AN (counter[3]), .B (validIn), .C (counter[4]), .Y
       (n_44));
  NAND3BX1 g4302(.AN (n_41), .B (in[3]), .C (n_4), .Y (n_43));
  NAND2X1 g4303(.A (n_39), .B (n_10), .Y (n_42));
  MXI2X1 g4304(.A (in[0]), .B (in[1]), .S0 (n_16), .Y (n_49));
  MX2X1 g4305(.A (n_13), .B (n_19), .S0 (WrIndex[0]), .Y (n_48));
  NOR2X1 g4306(.A (n_37), .B (n_35), .Y (n_47));
  INVX1 g4307(.A (n_39), .Y (n_38));
  INVX1 g4308(.A (n_37), .Y (n_36));
  INVX1 g4311(.A (n_11), .Y (n_12));
  BUFX2 g4317(.A (n_35), .Y (n_11));
  BUFX2 g4321(.A (n_35), .Y (n_10));
  NOR2X1 g4322(.A (n_225), .B (RdIndex[0]), .Y (n_34));
  NOR2BX1 g4323(.AN (in[0]), .B (WrIndex[0]), .Y (n_33));
  NAND2X1 g4324(.A (in[2]), .B (n_4), .Y (n_32));
  NAND2X2 g4325(.A (mode), .B (n_16), .Y (n_41));
  OR2X1 g4326(.A (mode), .B (n_16), .Y (n_40));
  NOR2X1 g4327(.A (WrIndex[0]), .B (WrIndex[1]), .Y (n_39));
  NOR2X2 g4328(.A (n_6), .B (n_17), .Y (n_37));
  NOR2X1 g4329(.A (WrIndex[2]), .B (WrIndex[3]), .Y (n_35));
  INVX1 g4330(.A (n_30), .Y (n_29));
  INVX1 g4331(.A (n_28), .Y (n_27));
  INVX1 g4332(.A (n_26), .Y (n_25));
  NOR2X1 g4333(.A (counter[4]), .B (counter[3]), .Y (n_24));
  NAND2X1 g4334(.A (in[2]), .B (n_5), .Y (n_23));
  NOR2X1 g4335(.A (reset), .B (counter[0]), .Y (n_22));
  NOR2BX1 g4336(.AN (counter[3]), .B (counter[4]), .Y (n_21));
  NOR2X1 g4337(.A (mode), .B (n_13), .Y (n_20));
  NAND2X2 g4338(.A (mode), .B (WrIndex[1]), .Y (n_31));
  NAND2X1 g4339(.A (mode), .B (n_5), .Y (n_30));
  NOR2X2 g4340(.A (WrIndex[2]), .B (n_6), .Y (n_28));
  AND2X1 g4341(.A (n_1), .B (n_6), .Y (n_26));
  INVX1 g4342(.A (in[3]), .Y (n_19));
  INVX1 g4343(.A (reset), .Y (n_18));
  INVX1 g4344(.A (WrIndex[2]), .Y (n_17));
  INVX1 g4345(.A (WrIndex[0]), .Y (n_16));
  INVX1 g4349(.A (n_3), .Y (n_14));
  INVX1 g4350(.A (in[2]), .Y (n_13));
  INVX1 g4352(.A (WrIndex[3]), .Y (n_8));
  INVX1 g4358(.A (n_6), .Y (n_7));
  INVX2 g4361(.A (WrIndex[3]), .Y (n_6));
  INVX1 g4371(.A (n_5), .Y (n_4));
  INVX2 g4373(.A (WrIndex[1]), .Y (n_5));
  INVX1 drc_bufs4374(.A (n_9), .Y (n_3));
  INVX1 drc_bufs4376(.A (n_2), .Y (n_9));
  BUFX2 drc_bufs4385(.A (WrIndex[2]), .Y (n_1));
  NOR2BX1 g2390(.AN (n_29), .B (n_48), .Y (n_0));
  AOI222X1 g4386(.A0 (buffer[10]), .A1 (n_95), .B0 (n_28), .B1 (n_97),
       .C0 (n_0), .C1 (n_26), .Y (n_228));
  AO22X1 g4387(.A0 (n_37), .A1 (n_97), .B0 (n_0), .B1 (n_28), .Y
       (n_229));
endmodule

