
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.21 - 15.20-s010_1
// Generated on: May  3 2016 22:42:30

// Verification Directory fv/rsc 

module rsc(clk, in, x_out, z_out, rst_N, mode, valid_out);
  input clk, in, rst_N, mode;
  output x_out, z_out, valid_out;
  wire clk, in, rst_N, mode;
  wire x_out, z_out, valid_out;
  wire IN, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, d1, d2, d3, n_0;
  wire n_1, n_2, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_15, n_22;
  XOR2X1 g118(.A (n_22), .B (d1), .Y (n_8));
  XNOR2X1 g119(.A (n_7), .B (n_1), .Y (n_22));
  XNOR2X1 g123(.A (d2), .B (d3), .Y (n_7));
  DFFTRX2 d3_reg(.CK (clk), .D (d2), .RN (rst_N), .Q (d3), .QN
       (UNCONNECTED));
  DFFHQX1 d2_reg(.CK (clk), .D (n_5), .Q (d2));
  DFFTRXL IN_reg(.CK (clk), .D (rst_N), .RN (in), .Q (UNCONNECTED0),
       .QN (IN));
  DFFX4 valid_out_reg(.CK (clk), .D (rst_N), .Q (UNCONNECTED1), .QN
       (n_6));
  INVX6 g129(.A (n_6), .Y (n_9));
  AND2X1 g130(.A (d1), .B (rst_N), .Y (n_5));
  BUFX12 drc_bufs(.A (n_2), .Y (n_4));
  BUFX20 drc_bufs132(.A (n_9), .Y (valid_out));
  BUFX20 drc_bufs138(.A (n_4), .Y (z_out));
  BUFX12 drc_bufs139(.A (n_1), .Y (n_15));
  MXI2X2 g2(.A (IN), .B (n_7), .S0 (mode), .Y (n_1));
  XOR2X1 g143(.A (d3), .B (n_8), .Y (n_2));
  DFFQX1 d1_reg(.CK (clk), .D (n_0), .Q (d1));
  AND2X1 g57(.A (n_22), .B (rst_N), .Y (n_0));
  BUFX20 drc_bufs144(.A (n_15), .Y (x_out));
endmodule

